<template>
  <div class="main">
    <div class="main-body">
      <div class="policy-body">
        <div class="upper-div">
          <h1>Data Processing Agreement</h1>

          <p class="last-updated">Last updated: October 29, 2023</p>

          <p class="message-1">
            This Privacy Policy includes important information about your
            personal data and we encourage you to read it carefully.
          </p>
        </div>

        <div class="inner-div">
          <div class="policy-content-box">
            <div class="policy-content">
              <div>
                <strong>INTRODUCTION</strong>
                <p>
                  These Data Processing Terms (“Data Terms”) apply to the
                  Services (defined hereunder) provided by Regenfi Labs Private
                  Limited, a private limited company, incorporated under the
                  provisions of the Companies Act, 2013, having its registered
                  office at House No. 43, Block- G, Landmark NA Sultanpuri, New
                  Delhi - 110041, India (“Data Processor” or “We” or “Us” or
                  “Our”).
                </p>
                <p>
                  For the purpose of these Data Terms, wherever the context so
                  requires the term “You”, “you” “Your”, and “your” shall mean
                  and include any entity or its representatives that avail the
                  Service(s) on the Platform for commercial purposes and shares
                  Personal Data (as defined below).
                </p>
                <p>
                  Any terms used herein that begin with a capitalized letter
                  shall have such meaning as assigned to it under the Business
                  Terms or under the respective clauses of this Data Terms.
                </p>
                <p>
                  The Data Terms contained in this electronic record read with
                  the Business Terms of, as available and uploaded on the
                  Platform, or any specific terms and conditions, as applicable
                  or relating to the Services which are incorporated herein by
                  reference, shall constitute the entire legally and binding
                  agreement between You and Us in connection with the access,
                  visit, or usage of the Platform for availing the Services on
                  the Platform in any manner unless a mutual agreement executed
                  between You and Us states otherwise. You are requested to read
                  these Data Terms carefully before accepting them.
                </p>
                <p>
                  This electronic record is generated by a computer system and
                  does not require any physical or digital signatures. This
                  electronic record is published in accordance with the relevant
                  provisions of the Information Technology Act, 2000 (“IT Act”)
                  and rules made thereunder.
                </p>
                <p>
                  IF YOU DO NOT AGREE WITH THESE DATA TERMS, THEN PLEASE REFRAIN
                  FROM USING AND ACCESSING THE PLATFORM AND AVAILING SERVICES ON
                  THE PLATFORM.
                </p>
                <p>
                  This Data Terms applies where and only to the extent that We
                  process Personal Data and/or Customer Data on behalf of You in
                  the course of providing the Services subject to the applicable
                  Data Protection Laws.
                </p>
                <p>
                  You are solely responsible and answerable to the User whose
                  Personal Data and/or Customer Data is shared with Us, and We
                  shall have no liability whatsoever towards such User.
                </p>
                <p>
                  You agree that the Data Processor may engage Sub-processors to
                  process Personal Data and Customer Data on Your behalf to
                  efficiently provide the Services to You.
                </p>
              </div>
              <div>
                <strong>DEFINITION</strong>
                <p>
                  “Affiliate” means an entity that directly or indirectly
                  Controls, is Controlled by, or is under common Control with an
                  entity.
                </p>
                <p>
                  “Business Day(s)” shall mean any day other than a Sunday or a
                  day on which scheduled commercial banks in Delhi, India, are
                  authorized or required by Law to be closed.
                </p>
                <p>
                  “Control” means an ownership, voting, or similar interest
                  representing 50 % (fifty percent) or more of the total
                  interests outstanding of the entity in question. The term
                  “Controlled” shall be construed accordingly.
                </p>
                <p>
                  “Customer Data” means any data You provide to Us to process on
                  Your behalf, in the course of providing the Services.
                </p>
                <p>
                  “Data Protection Law” means all data protection and privacy
                  laws and regulations applicable to the processing of Personal
                  Data in the Territory.
                </p>
                <p>
                  “Data Subject” (also referred to as “Individual” or
                  “Individuals”) means any User from whom You collect, use,
                  and/or process Personal Data for their business purpose. It
                  includes the information sought from the employees, clients,
                  client customers, agents, and contractors.
                </p>
                <p>
                  Government” or “Governmental Authority” means any statutory
                  authority, Government department, agency, commission, board,
                  tribunal, court, or any other entity in India authorized to
                  make Laws.
                </p>
                <p>
                  “Law” or “Laws” includes all applicable statutes, enactments,
                  acts of the legislature or parliament, laws, ordinances,
                  rules, by-laws, regulations, notifications, guidelines,
                  policies, directions, directives, and orders of any Government
                  Authority, tribunal, board or court, as amended from time to
                  time, in India.
                </p>
                <p>
                  “Person” shall mean any natural person, limited or unlimited
                  liability company, corporation, partnership (whether limited
                  or unlimited), proprietorship, Hindu Undivided Family, trust,
                  union, association, society, foundation, Government, or any
                  agency or political subdivision thereof or any other entity
                  that may be treated as a person under applicable Law.
                </p>
                <p>
                  “Personal Data” means any Customer Data relating to an
                  identified or identifiable natural person to the extent such
                  information is protected as personal data under applicable
                  Data Protection Law.
                </p>
                <p>
                  “Processor” here means Us, the Data Processor who processes
                  Personal Data on behalf of You as required to provide the
                  Services.
                </p>
                <p>
                  “Sub-processor” means any Processor engaged by the Data
                  Processor or its Affiliates to assist in fulfilling its
                  obligations with respect to providing the Services pursuant to
                  this Agreement.
                </p>
              </div>
              <div>
                <strong>INTERPRETATION</strong>
                <p>
                  Any reference to the singular includes a reference to the
                  plural and vice versa unless explicitly provided for
                  otherwise, and any reference to the masculine includes a
                  reference to the feminine and vice versa.
                </p>
                <p>
                  Headings and captions are used for convenience only and shall
                  not affect the interpretation of this Data Terms.
                </p>
                <p>
                  Any reference to any provision of Law herein is a reference to
                  it as it may have been, or may from time to time be, amended,
                  modified, consolidated, or re-enacted.
                </p>
                <p>
                  Any reference to a natural person shall, unless repugnant to
                  the context, include his heirs, executors, and permitted
                  assignees.
                </p>
              </div>
              <div>
                <strong>YOUR OBLIGATION</strong>
                <p>You are obligated to ensure that:</p>
                <p>
                  a) The Personal Data and the Customer Data have been obtained
                  by it through lawful means.
                </p>
                <p>
                  b) It has communicated to the User that You will be using,
                  storing, accessing, or processing Customer Data and Personal
                  Data, only for the approved purposes and secure all necessary
                  notices, permissions, and consents including maintaining a
                  published privacy policy; in compliance with the Data
                  Protection Laws and any other applicable privacy Laws, to
                  collect, use, and share, Customer’s Data.
                </p>
                <p>
                  c) Immediately notify the Data Processor, if any of its Users
                  request for withdrawal of processing of Customer Data.
                </p>
                <p>
                  d) Ensure Customer Data and Personal Data are processed only
                  on a need-to-know basis, by authorized personnel. These
                  authorized personnel must be fully trained to take care and
                  handle the Customer Data and Personal Data, must be committed
                  to confidentiality; and must also adhere to their
                  responsibilities related to the processing of the Personal
                  Data as required by Data Protection Laws.
                </p>
              </div>
              <div>
                <strong>OUR OBLIGATION</strong>
                <p>The Data Processor agrees and acknowledges that:</p>
                <p>
                  a) Ensure that the Processing is done only to process Customer
                  Data and Personal Data: Only for the approved purposes within
                  the Territory and must secure all necessary notices,
                  permissions, and consents including maintaining a published
                  privacy policy; in compliance with the Data Protection Laws
                  and any other applicable privacy Laws, to collect, use, and
                  share, Customer’s Data.
                </p>
                <p>
                  b) Notify You if it is unable to execute Your instruction(s)
                  due to any Law; or if there are any added requirements imposed
                  under the Law requiring the Data Processor to further process
                  Customer Data and Personal Data.
                </p>
                <p>
                  c) Ensure Customer Data are processed only on a need-to-know
                  basis, by authorized personnel. These authorized personnel
                  must be fully trained to take care and handle the Customer
                  Data and Personal Data, must be committed to confidentiality;
                  and must also adhere to their responsibilities related to the
                  processing of the Personal Data as required by Data Protection
                  Laws and this Agreement.
                </p>
                <p>
                  Deletion/Return of Customer Data and Personal Data: The Data
                  Processor shall promptly destroy any hard copies, notes,
                  electronic or digital copies or extracts thereof, retaining
                  only necessary copies for archival purposes thereof, for
                  auditing and/or legal requirements or as a part of a regular
                  backup program, for non-commercial purposes (in which case the
                  Confidentiality Clause will continue to be applicable for as
                  long as such Customer Data and Personal Data is in the
                  Receiving Party’s possession).
                </p>
              </div>
              <div>
                <strong>CONFIDENTIALITY &amp; DATA PRIVACY</strong>
                <p>
                  You agree that You and/ or Your employees, consultants, or
                  affiliates, shall not disclose any Confidential Information,
                  obtained hereunder to any third parties, without obtaining
                  prior written consent through in-built processes, as the case
                  may be, other than to its Affiliates, delivery partner,
                  agents, representatives, or advisors that are bound by
                  substantially similar non-disclosure obligations.
                </p>
                <p>
                  You are responsible for all activities occurring under its
                  Account. You must:
                </p>
                <p>
                  a) maintain the security of all Personal Data and Customer
                  Data you hold;
                </p>
                <p>b) keep Your devices and the Account safe and secure;</p>
                <p>
                  c) prevent unauthorized use of or access to Our Services and
                  such Personal Data and Customer Data;
                </p>
                <p>
                  d) immediately notify Us if You discover or suspect any
                  security breaches related to Our Services; and
                </p>
                <p>
                  e) We implement and follow generally recognized industry
                  standards and best practices for data and information security
                  to protect Our and Your data, network, and systems from
                  unauthorized access, use, or copying.
                </p>
              </div>
              <div>
                <strong>INDEMNITY</strong>
                <p>
                  You agree to indemnify, defend, and hold Us harmless from and
                  against all claims, actions, suits, demands, damages, losses,
                  costs, and expenses (including reasonable legal costs and
                  expenses) and proceedings arising from or related to the
                  breach of any of its obligations including compliance with
                  applicable Law in relation to the Personal Data and Customer
                  Data.
                </p>
                <p>
                  You will be solely responsible for any consequences that may
                  arise due to the sharing of Personal Data and Customer Data
                  with Us for availing our Services, and at all times abide by
                  the Business Terms and other policies as mentioned in the
                  Platform and applicable Law.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.main {
  margin-left: 77px;

  margin-top: 20px;
  font-family: "Lato" !important;
}

.upper-div {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.logo {
  margin-top: 30px;
}

.main-body {
  margin-top: 14px;
  display: flex;
  flex-direction: row;
  gap: 100px;
}
.policy-content-box {
  margin-top: 10px;
  height: 400px;
  overflow-y: scroll;
  border: 1px solid #ccc;
  padding-left: 10px;
  padding-right: 10px;
  padding-bottom: 10px;
width: 655px;

}

ul {
  list-style-type: none;
}

.sidebar {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.sidebar-content {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-left: 15px;
}

.active {
  color: rgba(91, 112, 175, 1);
}

.policy-body {
  margin-left: 400px;
  width: 55%;
  height: 600px;
}

.last-updated {
  font-size: 18px;
  font-weight: 600;
  line-height: 21.6px;
  color: rgba(91, 112, 175, 1);
}

.message-1 {
  font-size: 18px;
  font-weight: 400;
  line-height: 21.6px;
}

.introduction {
  font-weight: 600;
  font-size: 26px;
  line-height: 31.2px;
}

.policy-content {
  font-size: 18px;
  line-height: 21.6px;
  margin-top: 15px;
  margin-left: 3px;
  display: flex;
  flex-direction: column;
  gap: 18px;
  text-align: justify;
  font-family: Lato !important;
}

.bold {
  font-weight: 600;
}
</style>
