<template>
  <div class="main">
    <div class="main-body">
      <div class="policy-body">
        <div class="upper-div">
          <h1>Terms of Use (Business)</h1>

          <p class="last-updated">Last updated: October 29, 2023</p>

          <p class="message-1">
            This Privacy Policy includes important information about your
            personal data and we encourage you to read it carefully.
          </p>
        </div>

        <div class="inner-div">
          <div class="policy-content-box">
            <div class="policy-content">
              <div>
                <strong>INTRODUCTION</strong>
                <p>
                  These business terms of use (“Business Terms”) apply to the
                  Business Services (defined hereunder) provided by Regenfi Labs
                  Private Limited, a private limited company, incorporated under
                  the provisions of the Companies Act, 2013, having its office
                  at 91Springboard, Plot No. D, 107, Vyapar Marg, D Block, Sector 2, Noida,
                  Uttar Pradesh-201301, India (“Company”, “We”, “we”, “Us” or “Our”),
                  to You and the company or the business that You are authorized
                  to represent (“You”, “you” “Your”, “your” or “Business”).
                </p>
                <p>
                  The Business Terms contained in this electronic record, read
                  along with other policies as available and uploaded on the
                  Platform (defined hereunder), or any specific terms and
                  conditions, as applicable or relating to the Business Services
                  which are incorporated herein by reference, shall constitute
                  the entire legally and binding agreement between You and Us,
                  in connection with the access, visit, or usage of the Platform
                  for availing the Business Services in any manner unless a
                  mutual agreement executed between You and Us states otherwise.
                </p>
                <p>
                  You represent and warrant that You have the right, authority,
                  and capacity to enter into the Business Terms (on behalf of
                  the entity that You represent). You are requested to read
                  these Business Terms carefully before accepting them.
                </p>
                <p>
                  This electronic record is generated by a computer system and
                  does not require any physical or digital signatures. This
                  electronic record is published in accordance with the relevant
                  provisions of the Information Technology Act, 2000 (“IT Act”)
                  and rules made thereunder.
                </p>
                <p>
                  IN CASE YOU DO NOT AGREE WITH THESE BUSINESS TERMS, THEN
                  PLEASE REFRAIN FROM USING AND ACCESSING THE PLATFORM AND
                  AVAILING SERVICES ON THE PLATFORM.
                </p>
                <p>
                  It is further clarified that by availing the Business Services
                  on the Platform, and/or visiting, viewing, accessing, or
                  otherwise using the Business Services or information created,
                  collected, compiled, or submitted to the Platform, You are
                  deemed to have agreed to these Business Terms and all the
                  policies of the Platform.
                </p>
                <p>
                  It is hereby clarified that We may, from time to time, change
                  provisions related to the Business Services which also include
                  changing the extent and scope of Business Services and/ or
                  including any other category of service or facility within the
                  term ‘Business Services’, at Our sole discretion. You can
                  determine when these Business Terms were last revised by
                  referring to ‘LAST UPDATED’ mentioned in these Business Terms.
                  Your continued use of the Platform shall be deemed to signify
                  Your acceptance of these provisions or amended provisions of
                  these Business Terms.
                </p>
              </div>

              <div>
                <strong>ADDITIONAL TERMS AND POLICIES</strong>
                <p>
                  These Business Terms incorporate by reference the following
                  policies and documents:
                </p>
                <p>Business Data Processing Terms; and</p>
                <p>Privacy Policy.</p>
                <p>
                  To the extent that any of the additional terms and policies
                  conflict with these Business Terms, the additional terms and
                  policies will govern.
                </p>
              </div>

              <div>
                <strong>DEFINITIONS</strong>
                <p>
                  “Business Account” shall mean an account created by You on Our
                  Platform to access Our Business Services;
                </p>
                <p>
                  “Business Day” shall mean any day other than a Sunday or a day
                  on which scheduled commercial banks in New Delhi are
                  authorized or required by Law to be closed.
                </p>
                <p>
                  “Business Services” here refers to Our products and Services
                  as provided to Your Business.
                </p>
                <p>
                  “Confidential Information” here refers to the Business
                  Services, content, and services made available by Us, any
                  non-public information relating to the features and
                  functionality of Our Company and Our Business Services, and
                  all information clearly identified as confidential at the time
                  of the disclosure.
                </p>
                <p>
                  The “Effective Date” of the Business Terms of is the date
                  which is the earlier of:
                </p>
                <p>
                  Your initial access to any Business Services through any
                  online registration, downloading and initiating the
                  integration process; or
                </p>
                <p>
                  the effective date of any order form, as applicable,
                  referencing the Business Terms; or
                </p>
                <p>
                  by clicking a box indicating explicit acceptance of the
                  Business Terms.
                </p>
                <p>
                  The Business Terms will govern Your initial access on the
                  Effective Date as well as any future access made by You with
                  that reference to the Business Terms.
                </p>
                <p>
                  “Law” or “Laws” includes all applicable statutes, enactments,
                  acts of the legislature or parliament, laws, ordinances,
                  rules, by-laws, regulations, notifications, guidelines,
                  policies, directions, directives, and orders of any Government
                  Authority, tribunal, board or court, as amended from time to
                  time, in India.
                </p>
                <p>
                  “Services” shall mean to include but not be limited to
                  information technology-related support provided by Us to You
                  in order to create a database for Your ease of reference so as
                  to enable project management such as its collection,
                  processing, and reporting.
                </p>
                <p>
                  “Person” shall mean any natural person, limited or unlimited
                  liability company, corporation, partnership (whether limited
                  or unlimited), proprietorship, Hindu Undivided Family, trust,
                  union, association, society, foundation, Government, or any
                  agency or political subdivision thereof or any other entity
                  that may be treated as a person under applicable Law.
                </p>
                <p>
                  “Platform” shall mean an information technology platform i.e.
                  both mobile-based application and website-based application,
                  that is inter alia engaged in providing Business Services on
                  or through the Platform.
                </p>
              </div>

              <div>
                <strong>INTERPRETATION</strong>
                <p>
                  Any reference to the singular includes a reference to the
                  plural and vice versa; any reference to one gender includes a
                  reference to other gender(s) unless explicitly stated
                  otherwise;
                </p>
                <p>
                  Headings and captions are used for convenience only and not
                  for interpretation of the Business Terms;
                </p>
                <p>
                  Any reference to a natural person shall include his/her heirs,
                  executors, and permitted assignees and any reference to a
                  juristic person shall, include its affiliates, successors, and
                  permitted assignees, unless repugnant to the context.
                </p>
              </div>

              <div>
                <strong>CREATION OF A BUSINESS ACCOUNT</strong>
                <p>
                  To access the Business Services, You must create a Business
                  Account which allows You access to the Business Services.
                </p>
                <p>
                  You agree to keep Your Business Account information current,
                  accurate, and complete so that We may send notices,
                  statements, and other information to You. You agree to
                  immediately notify Us of any unauthorized use, or suspected
                  unauthorized use of Your Account or any other form of breach
                  of security. We shall not be held liable for any loss or
                  damage arising from Your failure to comply with the above
                  requirements. If You provide any information that is untrue,
                  inaccurate, not current, incomplete or We have reasonable
                  grounds to suspect that such information is untrue,
                  inaccurate, not current or incomplete, or not in accordance
                  with the Business Terms herein and the other policies of
                  Platform, We shall have the right to indefinitely suspend or
                  terminate your Business Account or block Your access on the
                  Platform.
                </p>
                <p>
                  We have the right to seek documentation from You as part of
                  the Know Your Customer (“KYC”) process from time to time. Any
                  refusal or inordinate delay in submitting the
                  documents/information or resulting in violation of this
                  section allows Us to suspend Your access to the Business
                  Account or terminate Your Business Account in accordance with
                  the Termination Section.
                </p>
                <p>
                  You shall log out from your Business Account at the end of
                  each session in order to ensure complete security and secrecy
                  of Your data and Our Company’s data. The Business Account
                  information must be shared with only authorized personnel and
                  You shall solely be responsible for safeguarding the Business
                  Account, its passwords, and all the information and data
                  associated with such Business Account. For the safety of the
                  data, information in such Business Account and prevention of
                  any possibility of any unauthorized use thereof, You should
                  use a strong password and not disclose the password to any
                  third parties. You are solely responsible for maintaining the
                  confidentiality of your Business Account, display name, and
                  password and You are fully responsible for all activities that
                  occur under the same and We shall not be liable or responsible
                  whatsoever in this regard. You expressly agree that You will
                  immediately notify Us about any actual or potential
                  unauthorized use of Your Business Account, display name and
                  password, or any breach of security or any breach of the
                  Business Terms by a third party.
                </p>
                <p>
                  We are not liable for any loss to You caused by any
                  unauthorized use of the Business Account and, in this respect,
                  You shall indemnify Us for losses that We may incur from any
                  other party on account of such unauthorized or fraudulent use
                  of the Business Account.
                </p>
                <p>
                  If We reasonably believe that a Business Account and password
                  are being used or misused in any manner, We reserve the right
                  to cancel rights to access the Platform and/or the Services
                  immediately without notice and block access to all users of
                  the Business Account from that particular IP address. We shall
                  not be liable for any loss that You may incur as a result of
                  someone else using Your password or Business Account. However,
                  You could be held liable for all the losses, claims, and
                  liabilities incurred by Us due to someone else using Your
                  Business Account or password.
                </p>
                <p>
                  In the event You become aware of any breach of security or
                  unauthorized use of the Business Account, then You shall take
                  all the reasonable steps to inform Us with respect to such
                  unauthorized use of the Business Account and, in this regard,
                  We shall not be responsible for any liabilities that such You
                  may incur from the misuse of the Business Account or password
                  or any data and information contained therein. You agree that
                  We cannot and will not be liable for any loss or damage
                  arising from Your failure to comply with these Terms. In this
                  respect, You shall indemnify Us for losses that We may incur
                  from any other party on account of such unauthorized or
                  fraudulent use of the Business Account.
                </p>
                <p>
                  You agree to use the Business Services in compliance with Our
                  technical and product documentation and any other related
                  documentation provided by Us regarding use of Business
                  Services.
                </p>
              </div>

              <div>
                <strong>CONDITIONS TO USE THE PLATFORM</strong>
                <p>
                  These Platform shall be used by You subject to the following:
                </p>
                <p>
                  Compliance with applicable Law: You agree that You will act
                  lawfully, diligently, and honestly at all times when You
                  access and use the Platform and/or avail the Business Services
                  and will comply with applicable Law.
                </p>
                <p>
                  Modification of the Terms: Subject to applicable Law, We may
                  stop providing Business Services (or any part of Business
                  Services) permanently or temporarily, to You or may modify or
                  change the nature of Business Services and/or these Business
                  Terms without any prior notice to You. Your use of Business
                  Services following such modification shall constitute Your
                  deemed acceptance of such modifications. Suspension of whole
                  or part of Our Business Services, either permanently or
                  temporarily does not absolve You or others of any liabilities
                  incurred pursuant to breach of these Business Terms.
                </p>
                <p>
                  Age: For the use and access of the Platform, whether or not
                  for provisions of availing any of the Business Services on the
                  Platform, You must be 18 (eighteen) years of age or older to
                  use or visit the Platform, in any manner. For this purpose,
                  You agree that by visiting the Platform or accepting these
                  Business Terms, You represent and warrant to Us that You are
                  18 (eighteen) years of age or older and that You have the
                  right, authority, and capacity to use the Platform and agree
                  to and abide by the Business Terms as provided herein.
                </p>
                <p>
                  Your Rights: We do not claim any ownership of the information
                  that You submit through Your Business Account or through Us.
                  You may have the necessary rights to such information
                  including the right to grant the rights and licenses as
                  required by these Business Terms. It is hereby clarified that
                  all Your information and Your content will belong solely to
                  You, and only be used to enhance the provision of Business
                  Services. You are responsible for any data or content uploaded
                  by You onto the Platform. We do allow You to share Your
                  information with others and by doing so You acknowledge that
                  We will not be responsible for any misuse of it once it is
                  shared or made public. We reserve the right to edit or remove
                  any material submitted/ posted to the Platform, stored by You
                  on Our servers, or hosted or published on the Platform.
                </p>
                <p>
                  Our Rights: We own all copyrights, trademarks, domains, logos,
                  trade dress, trade secrets, patents, and other intellectual
                  property rights associated with Our Company. You may not use
                  Our copyrights, trademarks (or any similar marks), domains,
                  logos, trade dress, trade secrets, patents, and other
                  intellectual property rights unless You have Our express
                  written permission.
                </p>
                <p>
                  Your license to Us: In order to operate and provide the
                  Business Services to You, You hereby grant Us a worldwide,
                  non-exclusive, royalty-free, sub-licensable, and transferable
                  right to use, reproduce, distribute, and create derivative
                  works of Your information to enhance and improve Our Business
                  Services.
                </p>
                <p>
                  No disruption or harm to the Platform and/or Services: You
                  agree that You will not interfere with, jeopardize, disrupt,
                  or harm the Platform and/or Business Services and that You
                  will not intercept, expropriate, re-use, steal, or re-utilize
                  any system, data, or information comprised in or provided to
                  You via the Platform and/or Business Services and at all times
                  comply with the Business Terms and other policies of the
                  Platform.
                </p>
                <p>
                  Access to the Platform: We will provide You with any help You
                  may reasonably require to access the Platform but We shall not
                  be responsible if You are unable to access any section of the
                  Platform or any of the Business Services for any reason. We do
                  not guarantee You access to the Platform at any time and at
                  all times. We do not guarantee that while You are accessing
                  the Platform, Your access will be uninterrupted, without
                  delay/interference, secure and/or error-free, or operate as
                  set out and anticipated in these Business Terms. Accordingly,
                  We reserve the right, at any time, to suspend or discontinue
                  the Platform and/or any of the Business Services for any
                  reason without incurring any liability or obligation to You.
                </p>
                <p>
                  Communication Preferences: As part of Your relationship with
                  Us, You permit Us to use Your contact information to send You
                  electronic communications (such as messages, emails, and phone
                  calls via WhatsApp or otherwise) from Us including: (a)
                  notices about Your Business Account, password changes, payment
                  authorizations, and other transactional information; (b)
                  notices about updates to Our Business Terms; and (c)
                  information about products, services, surveys, events, news,
                  and promotions offered by Us were permitted by applicable Law.
                  If You do not wish for Us to communicate with You regarding
                  (c) above, You may opt out of future communications by
                  clicking the “unsubscribe” link in any such communication.
                </p>
                <p>
                  Third Parties Access: In the instance that You retain a third
                  party as Your service provider to manage Your access to the
                  Business Services, You represent and warrant that such third
                  party will only process data pursuant to Your instructions and
                  authorizations, and subject to a written agreement that
                  obligates such data processing to be in compliance with the
                  Business Terms. You represent that You are solely and fully
                  liable for all acts and omissions by such third parties
                  authorized by You and We shall not be liable for any misuse or
                  mishandling on the part of such third party.
                </p>
                <p>
                  Fees, Taxes, Invoicing, and Payment (if and when applicable)
                </p>
                <p>
                  Any fee schedule applicable as part of the Business Terms will
                  be provided to You through Your Business Account.
                </p>
                <p>
                  You shall be solely responsible for paying all fees and taxes
                  required by applicable Laws in connection with the performance
                  of any Business Services or invoices raised as part of the
                  Business Terms.
                </p>
              </div>

              <div>
                <strong>PLATFORM SERVICES</strong>
                <p>
                  You, after logging into the Business Account will be able to
                  use the Business Services. We do not guarantee any
                  verification of any data or any other information shared by
                  You on the Platform. We do not guarantee the authenticity, or
                  reliability of the Information and consider it as bonafide
                  secured information. In this regard, We shall not be
                  responsible for any liabilities that may arise from the misuse
                  of or reliance on the information by You and You must at all
                  times, indemnify Us in case of such allegations.
                </p>
                <p>
                  You are provided with tech-enabled system-generated assistance
                  in measurement, reporting, and verification so that You get a
                  fair idea about the status of Your project and are able to
                  plan accordingly. We do not guarantee any authenticity
                  regarding the output that is system-generated and is based on
                  the information shared by You. We shall not be responsible for
                  any liabilities that may arise from the reliance on the
                  information generated through the usage of the Business
                  Services, and You must at all times, indemnify Us in case of
                  such claims.
                </p>
                <p>
                  You hereby acknowledge that it is solely responsible for the
                  generated content and shall be solely liable for any
                  consequences arising out of using the Business Services by
                  providing information and sharing such generated content,
                  including, but not limited to any claims, costs, losses,
                  damages, expenses, judgments, any other possible conflicts,
                  disputes, or issues arising out of or related to such
                  generated content.
                </p>
                <p>
                  We use the information that We have only for enhancing Your
                  experience and only to the extent necessary in providing
                  Business Services.
                </p>
              </div>

              <div>
                <strong>COMPANY’S LEGAL AND PRIVACY RESPONSIBILITIES</strong>
                <p>
                  You may only use Our Business Services if You have ensured
                  that Your Use of Our Business Services complies with all
                  relevant laws including Laws that are applicable to You. It is
                  Your sole responsibility to determine and ensure Your
                  compliance with your legal obligations.
                </p>
                <p>
                  We make no representations or warranties that Our Business
                  Services meet the needs of entities regulated by Laws with
                  heightened confidentiality requirements for personal data,
                  such as financial, or legal services entities. You are at all
                  times solely responsible for providing all necessary data
                  disclosures, maintaining a privacy policy, and adhering to all
                  other requirements as per applicable Law.
                </p>
                <p>
                  You must make all bonafide efforts to comply with Our Privacy
                  Policy when You dealing with individual data by utilizing Our
                  Business Services. You must also secure all necessary rights,
                  consents, and permissions (for example, opt-in) to share your
                  customers’ contact and other personal data using Our Business
                  Services. We are not liable for any acts or omissions by Your
                  breach of any Law and You agree that You shall indemnify Us
                  for losses that We may incur from any other party on account
                  of such unauthorized or fraudulent use of such data.
                </p>
              </div>
              <div>
                <strong>INTELLECTUAL PROPERTY RIGHTS</strong>
                <p>
                  For the purpose of these Business Terms herein, the term,
                  “intellectual property rights” shall mean on a worldwide
                  basis, all patents, copyrights, trade secrets, service marks,
                  trademarks, trade names, trade dress, trademark applications
                  and registrations, internet domain names, design rights, and
                  all other proprietary and intellectual property rights as may
                  exist now and hereafter come into existence, and all renewals
                  and extensions thereof, regardless of whether any of such
                  rights arise under any applicable Law.
                </p>
                <p>
                  It is further acknowledged and agreed by You that all the
                  intellectual property rights in all material presented on the
                  Platform, including but not limited to text, audio, video or
                  graphical images, interfaces, graphics, design, compilation,
                  information, computer code, products, software, downloadable
                  software, trademarks, logos and all other materials appearing
                  on the Platform are Our property, or that of Our parent,
                  affiliates, and associates and are protected under applicable
                  Laws.
                </p>
                <p>
                  All titles and any intellectual property rights to the
                  Business Services or its modifications and amendments belong
                  to Us. We own all copyrights, trademarks, domains, logos,
                  trade dress, trade secrets, patents, and other intellectual
                  property rights associated with the Services. Except as
                  expressly stated herein, the Business Terms do not grant Our
                  intellectual property rights to the Business Services.
                </p>
                <p>It is hereby clarified and agreed by You that:</p>
                <p>
                  We own all the intellectual property rights in and relating to
                  the Business Services offered through the Platform and Your
                  use of the Platform and/or availing of Services does not grant
                  or confer You with any rights in relation to Our intellectual
                  property rights or Our affiliates or licensor’s or suppliers’
                  intellectual property rights;
                </p>
                <p>
                  the structure of Our Platform shall not be reproduced,
                  distributed or published, in whole or in part, by You for any
                  purpose; other than in connection with Your permitted use of
                  the Platform and/ or availing of Business Services, You shall
                  not copy, reproduce, download, publish, adapt, create
                  derivative works, re-publish, post, broadcast, record, print,
                  commercially exploit, transmit, edit, communicate to the
                  public or distribute in any other way, any intellectual
                  property rights or content in relation to the Platform and/ or
                  availing of the Business Services or the computer codes or
                  elements which comprise the Platform;
                </p>
                <p>
                  by using, accessing, or visiting Our Platform and/ or availing
                  the Business Services, You acknowledge and agree that the
                  general layout, content and design of the Platform is
                  protected by copyrights, trademarks, service marks, patents or
                  other proprietary rights and laws and these Terms does not
                  grant to You any rights to any intellectual property rights in
                  respect of the Platform or any content;
                </p>
                <p>
                  You cannot create any derivative work or technology based upon
                  any Our intellectual property rights, confidential or Our
                  proprietary information; and
                </p>
                <p>
                  Other than as set out in this clause and the Platform’s
                  policies, You are not permitted to use any of Our intellectual
                  property rights without Our (and Our affiliates, licensor’s or
                  suppliers) prior written consent.
                </p>
                <p>
                  We may take action against You or with respect to Your
                  Business Account, including disabling or suspending Your
                  Business Account if You clearly or repeatedly infringe the
                  intellectual property rights of others or where We are
                  required to do so for legal reasons. Disabling or suspending
                  Your Business Account will be in accordance with these
                  Business Terms and as per applicable Law.
                </p>
                <p>
                  You acknowledge that You are responsible for and will release
                  Us from any and all liabilities, losses, claims and damages
                  that may arise out of or in connection with any infringement
                  of Our intellectual property rights or that of third parties,
                  by You. You further agree to hold Us harmless and indemnify Us
                  in this regard.
                </p>
                <p>We may also:</p>
                <p>
                  compile statistical and other information related to the
                  performance, operation, and use of the Business Services;
                </p>
                <p>
                  use data collectively via the Business Services in aggregated
                  form for security and operations management, to create
                  statistical analyses, and for research and development
                  purposes (“Service Analyses”).
                </p>
                <p>
                  Such Service Analyses will not incorporate any Confidential
                  Information in a form that could serve to identify the
                  business or any individual, and Service Analyses do not
                  constitute personal data. We retain all intellectual property
                  rights in relation to Our Service Analyses.
                </p>
              </div>

              <div>
                <strong>CODE OF CONDUCT</strong>
                <p>
                  Under these Business Terms, You agree not to host, display,
                  upload, modify, publish, transmit, update, or share any
                  information that:
                </p>
                <p>
                  • belongs to another Person and in relation to which it does
                  not have any right of use;
                </p>
                <p>
                  • infringes intellectual property rights (including any
                  patent, trademark, copyright or other proprietary rights) of
                  any Person and privacy rights of any individual;
                </p>
                <p>• is false or misleading in any way;</p>
                <p>• violates any Law;</p>
                <p>• harasses or advocates harassment of another Person;</p>
                <p>
                  • promotes illegal activities or abusive, obscene, defamatory
                  or libelous conduct;
                </p>
                <p>• solicits illegal activities;</p>
                <p>• harms minors in any way;</p>
                <p>
                  • deceives or misleads the other users of the Platform about
                  the origin of messages or communicates any information which
                  is grossly offensive or menacing in nature;
                </p>
                <p>
                  • threatens the unity, integrity, defence, security or
                  sovereignty of India, friendly relations with foreign states,
                  or public order or causes incitement to the commission of any
                  cognizable offence or prevents investigation of any offence or
                  is insulting any other nation;
                </p>
                <p>
                  • promotes an illegal or unauthorized copy of another person's
                  copyrighted work;
                </p>
                <p>
                  • provides material that exploits people in a sexual, violent
                  or otherwise inappropriate manner or solicits personal
                  information from anyone;
                </p>
                <p>
                  • provides instructional information about illegal activities
                  such as making or buying illegal weapons, violating someone’s
                  privacy, or providing or creating computer viruses;
                </p>
                <p>
                  • tries to gain unauthorized access or exceeds the scope of
                  authorized access to the Platform or solicits passwords or
                  personal identifying information for commercial or unlawful
                  purposes from other users;
                </p>
                <p>
                  • refers to any website or URL that, in our sole discretion,
                  contains material that is inappropriate for the Platform or
                  any other website, application, or software that contains
                  content that would be prohibited or violates the letter or
                  spirit of these Business Terms.
                </p>
                <p>You represent and warrant that You:</p>
                <p>
                  • will use Our Business Services solely for business,
                  commercial, and authorized purposes and not for personal use;
                </p>
                <p>
                  • will only provide registration information associated with
                  Your Business;
                </p>
                <p>
                  • have not been previously suspended or removed from creating
                  any Business Accounts, accessing the Business Services or
                  engaging in any activity that could result in suspension or
                  removal;
                </p>
                <p>
                  • have submitted all required registration information and
                  documentation, which is truthful and accurate;
                </p>
                <p>• have maintained the accuracy of such information.</p>
                <p>You agree not to:</p>
                <p>
                  • reveal/disclose confidential or proprietary information of
                  other Users, the Company, Platform or any third party when You
                  receive or come in possession of such confidential or
                  proprietary information;
                </p>
                <p>
                  • Incorporate any computer contaminant, software virus, or any
                  computer code, file or program on the Platform designed to
                  interrupt, destroy, or limit the functionality of the
                  Platform;
                </p>
                <p>
                  • incorporate or introduce any program on the Platform that
                  might infringe the intellectual property rights of any other
                  user and/or of Our Company/ Platform;
                </p>
                <p>
                  • download, copy, reproduce any file or information available
                  on the Platform which You know, or reasonably should know,
                  cannot be legally reproduced, displayed, performed, and/or
                  distributed;
                </p>
                <p>
                  • in any way, deface or vandalize the Platform or prevent or
                  restrict others from using the Platform;
                </p>
                <p>
                  • infringe any patent, trademark, copyright or other
                  proprietary rights or third party’s trade secrets or rights of
                  publicity or privacy, of Our Company, other users of the
                  Platform or any third Party. You agree that it has valid
                  rights and title in any and information and has not infringed
                  on any intellectual property rights belonging to any Person
                  and, in this respect, You agree that You will indemnify Us or
                  Our affiliates for all claims arising out of any information
                  that You posted on the Platform;
                </p>
                <p>
                  • impersonate any person or entity, or falsely state or
                  otherwise misrepresent themselves or their affiliation with
                  any person or entity;
                </p>
                <p>
                  • directly or indirectly, offer, attempt to offer, trade or
                  attempt to trade in any item, the dealing of which is
                  prohibited or restricted in any manner under the provisions of
                  any applicable Law;
                </p>
                <p>
                  • create liability for Our Company/ Platform or cause Our
                  Company/ Platform to lose (in whole or in part) the services
                  of its internet service provider or other suppliers;
                </p>
                <p>
                  It is also clarified that you shall not use any “deep-link”,
                  “page-scrape”, or use any other automatic device, program,
                  algorithm, or methodology, or any similar or equivalent manual
                  process, to access, acquire, copy, or monitor any portion of
                  the Platform, or in any way reproduce or circumvent the
                  navigational structure or presentation of the Platform, to
                  obtain or attempt to obtain any materials, documents or
                  information through any means not purposely made available
                  through the Platform. We reserve the right to bar any such
                  activity.
                </p>
                <p>
                  You agree that you shall not attempt to gain unauthorized
                  access to any portion or feature of the Platform or any
                  feature pertaining to availing of Business Services or any
                  other systems or networks connected to the Platform or to any
                  server, computer, network, or to any Services offered on or
                  through the Platform, by hacking, password “mining” or any
                  other illegitimate means.
                </p>
                <p>
                  You agree that You shall not probe, scan, or test the
                  vulnerability of the Platform or any network connected to the
                  Platform nor breach the security or authentication measures on
                  the Platform or any network connected to the Platform. You may
                  not reverse look-up, trace or seek to trace any information on
                  any other user of or visitor to Platform, or any other
                  client/customer/user/member of the Company/ Platform including
                  any Business Account on the Platform not
                  owned/operated/managed by You, to its source, or exploit the
                  Platform or information made available or offered by or
                  through the Platform, in any way where the purpose is to
                  reveal any information, including but not limited to personal
                  identification or information, other than Your own
                  information, as provided for by the Platform.
                </p>
                <p>
                  You agree that You shall not make any negative, denigrating,
                  or defamatory statement and/or comment about the Company/
                  Platform or Our Business Services or the brand name or domain
                  name used by the Company/ Platform or otherwise engage in any
                  conduct or action that might tarnish the image or reputation
                  of the Company/ Platform or other users on the Platform or
                  other business partners of the Company or otherwise tarnish or
                  dilute any of the Company’s trade or service marks, trade
                  names and/or goodwill associated with such trade or service
                  marks, trade name as may be owned or used by the Platform.
                </p>
                <p>
                  You agree that You will not use the Platform or any content
                  thereof for any purpose which is unlawful or prohibited by the
                  Business Terms or to solicit the performance of any illegal
                  activity or other activity that infringes the rights of Our
                  Company/ Platform, its users and/or others third parties.
                </p>
                <p>
                  In the event, We have reasonable grounds to believe that Your
                  activities include any of the acts specified above, we may
                  initiate appropriate legal action against You as well as
                  notify the relevant regulatory or law enforcement authorities
                  where appropriate in addition to any other available remedies
                  under Law or equity, apart from restricting or suspending or
                  terminating Your use of the Platform.
                </p>
                <p>
                  You agree that you shall, at all times, ensure full compliance
                  with the applicable provisions of the IT Act, and the rules
                  thereunder as applicable and as amended from time to time and,
                  also all applicable Laws regarding the use of Business
                  Services. Further, You agree that you shall not solicit
                  (directly or indirectly) any other users of the Platform to
                  avail the Business Services of the Platform being displayed on
                  the Platform, either independently or through Our Company/
                  Platform.
                </p>
                <p>
                  You shall indemnify and hold harmless the Company, its owners,
                  licensees, affiliates, subsidiaries, group companies (as
                  applicable) and their respective officers, directors, agents,
                  and employees, from all losses, claims, damages, penalties,
                  costs, expenses, demands, actions (including reasonable
                  attorneys’ fees) suffered or incurred by Our Company/ Platform
                  due to or arising out of breach of these Business Terms and
                  other policies of the Platform.
                </p>
              </div>
              <div>
                <p>
                  <strong>PAYMENT TERMS</strong>
                </p>
                <p>
                  Please note that You can avail the Business Services on the
                  Platform by making payments (“Fee”) to Us. For the purpose of
                  making payments towards any Fee, You can make such payments by
                  (a) Credit/Debit Card; (b) Net Banking; or (c) any other mode
                  of electronic payment as provided on the Platform.
                </p>
              </div>
              <div>
                <p>
                  Any payments and transactions in respect of Business
                  Service(s) under these Business Terms may be facilitated by or
                  through third-party payment processors, online fund transfer
                  facility through banks or credit cards or mobile and
                  internet-based payment /commerce platforms or authorized
                  payment gateway networks as recognized and authorized by the
                  Reserve Bank of India (“Payment Facilitators”).
                </p>
              </div>
              <div>
                <p>
                  In this respect, it is clarified that the services of Payment
                  Facilitators are utilized for the purposes of making any
                  payment transaction in respect of Business Service(s) under
                  these Terms, and use of such services of Payment Facilitators
                  shall not render the Platform liable or responsible or assume
                  any liability, whatsoever in respect of any loss or damage,
                  arising directly or indirectly to You on account of (i) lack
                  of authorization for any transaction(s); (ii) exceeding the
                  pre-set limit mutually agreed by and between You and Your
                  bank; (iii) any payment issues arising out of the transaction;
                  (iv) decline of transaction for any reason; or (v) for any
                  reason whatsoever.
                </p>
              </div>
              <div>
                <p>
                  Subject to clause 14.6 of these Terms, in the event of any
                  claim for refund by You for any reason whatsoever, You shall
                  immediately intimate Us of the same. We shall duly assess Your
                  concern and determine the genuineness of it. If We determine
                  that any refund (excluding any transaction charges or other
                  such charges) if payable to You, then such refund (if any)
                  shall be effected by Us via Payment Facilitators or such other
                  means as We deem appropriate. No claims for refund shall be
                  made by You to the Payment Facilitator directly and no such
                  claims shall be entertained by Us.
                </p>
              </div>
              <div>
                <p>
                  <strong>SECURITY</strong>
                </p>
                <p>
                  All passwords are encrypted. When You create an account or
                  update Your password, the password is immediately encrypted
                  before being stored in Our database. Encryption is a process
                  that converts plain-text data (the user's password) into an
                  unreadable format using a cryptographic key. This ensures that
                  even if unauthorized individuals gain access to the database,
                  they will not be able to decipher the passwords without the
                  corresponding decryption key.
                </p>
              </div>
              <div>
                <p>
                  We also implement measures to protect the encryption keys,
                  limiting access to authorized personnel only. This adds an
                  extra layer of security to prevent potential data breaches. By
                  employing encryption techniques, we prioritize the
                  confidentiality and integrity of Your passwords, making it
                  significantly more challenging for malicious actors to exploit
                  any potential security vulnerabilities and compromise the
                  security of Your account. Our commitment to data security is
                  steadfast, and We continuously review and improve Our
                  practices to stay up-to-date with the latest security
                  standards.
                </p>
              </div>
              <div>
                <p>
                  We also use the following security measures to protect Your
                  information:
                </p>
                <ul>
                  <li>
                    Password Protection: Using password encryption in order to
                    safe access by authorized individuals;
                  </li>
                  <li>
                    Secure Development Practices: Following secure coding
                    practices during the development process helps reduce
                    vulnerabilities and ensures that potential security flaws
                    are identified and addressed early on;
                  </li>
                  <li>
                    Access Control and Authorization: Implement proper access
                    controls, ensuring that persons can only access the data and
                    features that are relevant to their roles;
                  </li>
                  <li>
                    Data Minimization: Collect and store only the data that is
                    necessary for the Business Services and the functionality of
                    the Platform, minimizing the potential impact of a data
                    breach;
                  </li>
                  <li>
                    Security Updates and Patches: Keep all software and systems
                    up-to-date with the latest security patches to protect
                    against known vulnerabilities;
                  </li>
                  <li>
                    Regular Backups: Regularly backing up data to prevent data
                    loss in case of system failures or ransomware attacks;
                  </li>
                  <li>
                    Privacy Policy and User Consent: The Privacy Policy outlines
                    the data collected, its usage, and Users' rights. Obtain
                    explicit User consent for data collection and processing;
                  </li>
                  <li>
                    Monitoring and Logging: Implement monitoring and logging
                    mechanisms to detect and respond to security incidents
                    promptly.
                  </li>
                </ul>
              </div>
              <div>
                <p>
                  In relation to the security of the data shared by You, You
                  must at all times adhere to applicable Law and comply with the
                  requirements mentioned in the Privacy Policy and Data
                  Processing Terms.
                </p>
              </div>
              <div>
                <p>
                  <strong>NON-DISCLOSURE</strong>
                </p>
                <p>
                  By virtue of the Business Terms, the parties may have access
                  to Confidential Information. Subject to the Termination
                  section, the party that receives the Confidential Information
                  agrees not to disclose the other’s Confidential Information
                  which is being disclosed by the other party.
                </p>
              </div>
              <div>
                <p>
                  A party’s Confidential Information shall not include
                  information that:
                </p>
                <ul>
                  <li>
                    is or becomes a part of the public domain through no act or
                    omission of the other party;
                  </li>
                  <li>
                    was in the other party’s lawful possession prior to the
                    disclosure and had not been obtained by the other party
                    either directly or indirectly from the disclosing party;
                  </li>
                  <li>
                    is lawfully disclosed to the other party by a third party
                    without restriction on the disclosure; or
                  </li>
                  <li>is independently developed by the other party.</li>
                </ul>
              </div>
              <div>
                <p>
                  We may disclose Confidential Information only to Our
                  employees, agents or subcontractors who are required to
                  protect it against unauthorized disclosure in a manner no less
                  protective than required under the Business Terms. This clause
                  will survive the termination of the Business Terms.
                </p>
              </div>
              <div>
                <p>
                  We may take action against You or with respect to Your
                  Business Account, including disabling or suspending Your
                  Business Account if You clearly or repeatedly infringe this
                  clause or where We are required to do so for legal reasons.
                  Disabling or suspending Your Business Account will be in
                  accordance with these Business Terms and as per applicable
                  Law.
                </p>
              </div>
              <div>
                <p>
                  <strong
                    >WARRANTIES, DISCLAIMERS, AND EXCLUSIVE REMEDIES</strong
                  >
                </p>
                <p>
                  You agree that You will use the Business Services at Your own
                  risk and subject to the following disclaimers.
                </p>
              </div>
              <div>
                <p>We do not undertake that:</p>
                <ul>
                  <li>
                    Business Services will be error-free or uninterrupted, or We
                    will correct all service errors;
                  </li>
                  <li>
                    Business Services will meet the Business’ requirements,
                    specifications or expectations. We acknowledge that We do
                    not control the transfer of data over communications
                    facilities, including the internet, and that usage of the
                    Business Services and transfer of data may be subject to
                    limitations, delays, and other problems inherent in the use
                    of such communications facilities;
                  </li>
                  <li>
                    We are not responsible for any delays, delivery failures, or
                    other damage resulting from such problems.
                  </li>
                </ul>
              </div>
              <div>
                <p>
                  For any breach of the Business Terms by Us, Your exclusive
                  remedy shall be the correction of the deficient services that
                  caused the breach of the Business Terms by Us, or, if We
                  cannot substantially correct the deficiency in a commercially
                  reasonable manner, the Business may terminate the Business
                  Terms on 14 (fourteen) Business Days’ written notice, and We
                  shall have no further liability to the Business.
                </p>
              </div>
              <div>
                <p>
                  To the extent not prohibited by Law, any warranties provided
                  under the Business Terms are exclusive, and all other
                  warranties or conditions, whether express or implied, are
                  expressly excluded, including for software, hardware, systems,
                  networks, or environments or for merchantability, satisfactory
                  quality, and fitness for a particular purpose.
                </p>
              </div>
              <div>
                <p>
                  <strong>INDEMNITY</strong>
                </p>
                <p>
                  In addition and not in derogation of the specific indemnities
                  provided by You to Us under these Business Terms and/or
                  policies of the Platform, You agree to indemnify, defend, and
                  hold Us harmless along with Our affiliates, officers,
                  directors, employees, consultants, representatives,
                  shareholders, contractors, users, and agents, etc. against any
                  or all losses, liabilities, claims, damages, demands, costs,
                  and expenses (including legal fees and disbursements in
                  connection therewith and interest chargeable thereon) arising
                  out of or in connection with any claim, suit, action, or other
                  proceeding brought against Us or such party, to the extent
                  such losses are based on or arising out of or in connection
                  with:
                </p>
              </div>
              <div>
                <p>
                  any breach or non-performance of any of the Business Terms
                  and/ or other policies of the Platform with respect to the use
                  and access of the Platform and/ or availing of Business
                  Services;
                </p>
                <p>
                  truthfulness and correctness of the information provided by
                  You at the time of registration and/ or at any time during
                  availing of the Business Services; and/or
                </p>
                <p>
                  breach of any third-party rights (including, but not limited
                  to, claims in respect of defamation, invasion of privacy, or
                  infringement of any other intellectual property right) by You.
                </p>
              </div>
              <div>
                <p>
                  <strong>TERMINATION</strong>
                </p>
                <p>
                  You agree that We, at Our sole discretion and for any,
                  including inter alia without limitation if you breach these
                  Business Terms, may terminate your access to and use of the
                  Business Service and/or Platform, at any time. You agree that
                  any termination of your access to the Platform and/ or
                  suspension/ termination of your Business Account may be
                  effected without prior notice, and in this respect, We shall
                  not be liable to you for any such termination. Your right to
                  use the Platform immediately ceases upon termination of your
                  access/use of the Platform and/or Services.
                </p>
              </div>
              <div>
                <p>
                  The provisions of these Business Terms shall continue to apply
                  until terminated by either of the Party. In case You want to
                  terminate these Business Terms, then You may do so by: (a) not
                  accessing the Platform and/or Services; or (b) closing the
                  Account.
                </p>
              </div>
              <div>
                <p>
                  We reserve the right to, at any time, and with or without
                  notice, terminate these Business Terms against You, if there
                  are:
                </p>
                <ul>
                  <li>
                    breach of any of the applicable Laws: or the provisions of
                    these Business Terms, the terms of the Privacy Policy or any
                    other terms, conditions, or policies that may be applicable
                    from time to time (or have acted in a manner that clearly
                    shows that You did not intend to, or is unable to, comply
                    with the same);
                  </li>
                  <li>
                    Platform is unable to verify or authenticate any information
                    provided to the Platform by You;
                  </li>
                  <li>
                    We believe, at our sole discretion, that Your actions may
                    cause legal liability to Us, (or any of Our affiliates,
                    independent contractors, service providers, consultants,
                    licensors, agents, and representatives) or that they are
                    contrary to the interests of the Platform;
                  </li>
                  <li>We are required to do so by Law; or</li>
                  <li>
                    if You fails to provide (or after providing such consent,
                    later revokes) the consents necessary or desirable for Us to
                    provide the Services to You.
                  </li>
                </ul>
              </div>
              <div>
                <p>
                  <strong>Effect of Termination:</strong> Upon any termination
                  or expiration of the Business Terms:
                </p>
                <p>
                  You must immediately cease using the Business Services; and
                </p>
                <p>
                  at the disclosing party’s request, the receiving party will
                  promptly return or delete any of the disclosing party’s
                  Confidential Information in its possession.
                </p>
              </div>
              <div>
                <p>
                  <strong>LIMITATION OF LIABILITY</strong>
                </p>
                <p>
                  You shall access the Platform and avail Business Services
                  provided on the Platform voluntarily and at Your own risk. We
                  shall, under no circumstances be held responsible or liable on
                  account of any loss or damage sustained (including but not
                  limited to any accident, injury, death, loss of property of
                  any of Your employee, User or any other person or entity)
                  during the course of access to Business Services.
                </p>
              </div>
              <div>
                <p>
                  By accessing the Platform and/or availing the Business
                  Services, You hereby release from and agree to indemnify Us
                  and/ or any of Our directors, employees, partners, associates
                  and licensors, from and against all liability, cost, loss or
                  expense arising out their access to the Platform and availing
                  of Business Services including (but not limited to) personal
                  injury and damage to property and whether direct, indirect,
                  consequential, foreseeable, due to some negligent act or
                  omission on their part, or otherwise.
                </p>
              </div>
              <div>
                <p>
                  You shall be solely responsible for any consequences which may
                  arise due to their access of the Platform and availing of the
                  Business Services by conducting an illegal act or due to
                  non-conformity with these Business Terms and other rules and
                  regulations in relation to Business Services and/ or policies
                  of the Platform, including provision of incorrect address or
                  other personal details.
                </p>
              </div>
              <div>
                <p>
                  In consideration of Us allowing You to access the Business
                  Services, to the maximum extent permitted by Law, You waive
                  and release each and every right or claim, all actions, causes
                  of actions (present or future) that You may have against Us,
                  Our respective agents, directors, officers, business
                  associates, group companies, sponsors, employees, or
                  representatives for all and any injuries, accidents, or
                  mishaps (whether known or unknown) or (whether anticipated or
                  unanticipated) arising out of the provision of Business
                  Services.
                </p>
              </div>
              <div>
                <p>
                  In no event shall We, or Our officers, directors, employees,
                  or partners be liable to You or any third party for any
                  special, incidental, indirect, consequential or punitive
                  damages whatsoever, including those resulting from loss of
                  use, data or profits, whether or not foreseeable or whether or
                  not We have been advised of the possibility of such damages,
                  or based on any theory of liability, including breach of
                  contract or warranty, negligence or other tortious action, or
                  any other claim arising out of or in connection with Your use
                  of or access of the Platform and availing of the Business
                  Services.
                </p>
              </div>
              <div>
                <p>
                  You will be responsible for and release Us from any and all
                  liabilities, losses, claims and damages that may arise out of
                  or in connection with the disclaimers as mentioned under these
                  Business Terms and further agrees to hold harmless and
                  indemnify Us in this regard.
                </p>
              </div>
              <div>
                <p>
                  In no event shall Our total aggregate liability, to You or
                  Your Users, for any or all loss profits, consequential,
                  special, punitive, indirect or incidental damages, and causes
                  of action (whether in contract or tort, including, but not
                  limited to negligence, strict liability, product liability or
                  otherwise) arising from or in connection with these Business
                  Terms or due to use of the Platform exceed an aggregate amount
                  of INR 1000/- (Indian Rupees One Thousand only). We accept no
                  liability for any errors or omissions on behalf of You. The
                  foregoing limitations shall apply regardless of whether (i)
                  liability or damage is alleged for breach of contract,
                  tortious behavior, negligence, or under any other theory or
                  cause of action, and/or (ii) the party against which liability
                  or damages is sought was advised of the possibility thereof.
                </p>
              </div>

              <div>
                <p>
                  <strong>DISCLAIMER</strong>
                </p>
                <p>
                  YOU AGREE AND UNDERSTAND THAT THE PLATFORM IS PROVIDED BY US
                  ON AN “AS IS” AND “AS AVAILABLE” BASIS AND WE MAKE NO
                  REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
                  AS TO THE OPERATION OF THIS PLATFORM OR THE INFORMATION,
                  CONTENT INCLUDED ON THIS PLATFORM. YOU EXPRESSLY AGREE THAT
                  YOUR USE OF THIS PLATFORM IS AT YOUR SOLE RISK. WE RESERVE THE
                  RIGHT TO WITHDRAW OR DELETE ANY INFORMATION FROM THIS PLATFORM
                  AT ANY TIME IN OUR DISCRETION.
                </p>
              </div>
              <div>
                <p>
                  TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, WE
                  DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED. WE DOES NOT
                  WARRANT THAT THIS PLATFORM, ITS SERVERS, OR EMAIL/ OTHER
                  COMMUNICATION SENT FROM THE PLATFORM ARE FREE OF VIRUSES OR
                  OTHER HARMFUL COMPONENTS. WE WILL NOT BE LIABLE FOR ANY
                  DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS PLATFORM,
                  INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL,
                  PUNITIVE AND CONSEQUENTIAL DAMAGES.
                </p>
              </div>
              <div>
                <p>
                  TO THE EXTENT PERMITTED UNDER LAW, NEITHER WE NOR OUR
                  PARENT/HOLDING COMPANY, SUBSIDIARIES, AFFILIATES, DIRECTORS,
                  OFFICERS, PROFESSIONAL ADVISORS, EMPLOYEES SHALL BE
                  RESPONSIBLE FOR THE DELETION, THE FAILURE TO STORE, THE
                  MIS-DELIVERY, OR THE UNTIMELY DELIVERY OF ANY
                  INFORMATION/CONTENT OR MATERIAL.
                </p>
              </div>
              <div>
                <p>
                  <strong
                    >YOU AGREE THAT YOUR USE OF THE BUSINESS SERVICES SHALL BE
                    AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW,
                    WE, OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS EXCLUDE
                    ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE
                    SERVICES AND YOUR USE THEREOF.</strong
                  >
                </p>
              </div>
              <div>
                <p>
                  TO THE EXTENT PERMITTED UNDER LAW, WE SHALL NOT BE RESPONSIBLE
                  FOR ANY HARM RESULTING FROM DOWNLOADING OR ACCESSING ANY
                  INFORMATION/CONTENT OR MATERIAL AND THE QUALITY THEREOF.
                </p>
              </div>
              <div>
                <p>
                  WE DISCLAIM ANY AND ALL LIABILITY AND RESPONSIBILITY FOR, AND
                  IF YOU PAY FOR ACCESS TO THE BUSINESS SERVICES, THEN YOU WILL
                  NOT BE ENTITLED TO A REFUND AS A RESULT OF, ANY
                  INACCESSIBILITY TO THE PLATFORM OR UNAVAILABILITY OF THE
                  SERVICES OR THAT IS CAUSED BY OUR MAINTENANCE ON THE SERVERS
                  OR THE TECHNOLOGY THAT UNDERLIES OUR SITES, FAILURES OF
                  COMPANY'S SERVICE PROVIDERS (INCLUDING TELECOMMUNICATIONS,
                  HOSTING, AND POWER PROVIDERS), DEFECT IN TELECOMMUNICATION
                  NETWORK, INTERNET FAILURES, COMPUTER VIRUSES, NATURAL
                  DISASTERS OR OTHER DESTRUCTION OR DAMAGE OF OUR FACILITIES,
                  ACTS OF NATURE, WAR, CIVIL DISTURBANCE, OR ANY OTHER CAUSE
                  BEYOND OUR REASONABLE CONTROL.
                </p>
              </div>
              <div>
                <p>
                  ANY MATERIAL/CONTENT ACCESSED, DOWNLOADED, OR OTHERWISE
                  OBTAINED THROUGH THE PLATFORM IS DONE AT YOUR DISCRETION,
                  COMPETENCE, ACCEPTANCE, AND RISK, AND YOU WILL BE SOLELY
                  RESPONSIBLE FOR ANY POTENTIAL DAMAGE TO YOUR COMPUTER SYSTEM
                  OR LOSS OF DATA THAT RESULTS FROM DOWNLOAD OF ANY SUCH
                  MATERIAL/CONTENT.
                </p>
              </div>
              <div>
                <p>
                  THE PLATFORM SHALL MAKE BEST ENDEAVOURS TO ENSURE THAT THE
                  BUSINESSS SERVICES ARE ERROR-FREE AND SECURE, HOWEVER, NEITHER
                  WE NOR ANY OF OUR PARTNERS, LICENSORS OR ASSOCIATES MAKES ANY
                  WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS; THE
                  BUSINESS SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR
                  ERROR FREE; THE QUALITY OF THE SERVICES, INFORMATION/CONTENT,
                  OR OTHER MATERIAL THAT YOU OBTAIN THROUGH THE PLATFORM WILL
                  MEET YOUR EXPECTATIONS.
                </p>
              </div>
              <div>
                <p>
                  YOU AGREE AND ACKNOWLEDGE THAT INFORMATION SHARED BY YOU SHALL
                  BE THE PROPERTY OF THE USER AND YOU SHALL BE SOLELY
                  RESPONSIBLE FOR ANY UNAUTHORIZED USE OR MISUSE OF SUCH CONTENT
                  AND SHALL INDEMNIFY AND HOLD US HARMLESS FROM ANY CLAIM,
                  DAMAGE, LOSS, EXPENSE BROUGHT AGAINST, ACCRUED AND/OR INCURRED
                  BY US IN THIS REGARD.
                </p>
              </div>
              <div>
                <p>
                  TO THE EXTENT PERMITTED UNDER LAW, IN THE EVENT OF SUSPENSION
                  OR CLOSURE OF ANY BUSINESS SERVICES, YOU SHALL NOT BE ENTITLED
                  TO MAKE ANY DEMANDS, OR CLAIMS, OF ANY NATURE WHATSOEVER.
                </p>
              </div>
              <div>
                <p>
                  PLATFORM HAS EXERTED REASONABLE EFFORTS TO ENSURE THAT ALL
                  INFORMATION PUBLISHED ON THE WEBSITE/APP IS ACCURATE AT THE
                  TIME OF POSTING; HOWEVER, THERE MAY BE ERRORS IN SUCH
                  INFORMATION FOR WHICH WE SHALL HAVE NO LIABILITY. WE RESERVE
                  THE RIGHT TO REMOVE OR ALTER ANY OF THE INFORMATION CONTAINED
                  ON THE PLATFORM AT OUR SOLE DISCRETION. THE PLATFORM CANNOT
                  GUARANTEE THE ADEQUACY, CURRENCY, OR COMPLETENESS OF THE
                  PLATFORM CONTENT.
                </p>
              </div>
              <div>
                <p>
                  YOU EXPRESSLY AGREE AND ACKNOWLEDGE TO HOLD HARMLESS US IN
                  RESPECT OF ANY COST, CLAIMS, DAMAGE, LOSS OR EXPENSES ACCRUED,
                  SUFFERED, INCURRED BY THE COMPANY OR ANY THIRD PARTY ARISING
                  OUT OF OR IN CONNECTION WITH ANY SUCH COMMUNICATION,
                  INTERACTION, DEALINGS AND TRANSACTIONS BETWEEN YOU AND
                  THIRD-PARTY ADVERTISERS/ THIRD PARTY SERVICE PROVIDERS. YOU
                  ACKNOWLEDGE THAT WE DO NOT HAVE ANY CONTROL OVER SUCH DEALINGS
                  AND TRANSACTIONS AND PLAY NO DETERMINATIVE ROLE IN THE
                  PERFORMANCE WITH RESPECT TO THE SAME. THE COMPANY SHALL NOT BE
                  LIABLE FOR THE OUTCOMES OF SUCH COMMUNICATION, INTERACTION,
                  DEALINGS, AND TRANSACTIONS BETWEEN YOU AND THE THIRD-PARTY
                  ADVERTISERS/THIRD-PARTY SERVICE PROVIDERS.
                </p>
              </div>
              <div>
                <p>
                  <strong
                    >GOVERNING LAW, JURISDICTION AND DISPUTE RESOLUTION</strong
                  >
                </p>
                <p>
                  These Business Terms shall be governed by the laws of India.
                  Subject to Clause 19.2 below, the courts and tribunals of New
                  Delhi have exclusive jurisdiction to settle any dispute
                  arising out of or in connection with these Business Terms
                  (including any disputes regarding the existence, validity or
                  termination of these Business Terms).
                </p>
              </div>
              <div>
                <p>
                  If any dispute, controversy or claim arises under, out of, or
                  in relation to these Business Terms, including any dispute
                  concerning the formation, construction, interpretation, or
                  breach of these Business Terms, then such dispute shall at the
                  first instance be attempted to be resolved through mutual good
                  faith consultations. If the dispute is not resolved in this
                  manner within 45 (forty-five) Business Days of either party
                  (You or We) sending a notice in this regard to the other party
                  of such dispute, then the dispute shall be resolved by binding
                  arbitration under the provisions of the Arbitration &
                  Conciliation Act 1996, by a sole arbitrator who shall be
                  appointed by Us and whose decision shall be final and binding
                  upon all the concerned parties. The seat and venue of the
                  arbitration proceedings shall be New Delhi, India.
                </p>
              </div>

              <div>
                <p>
                  <strong>OTHER TERMS</strong>
                </p>
                <p>
                  If for any reason, a court of competent jurisdiction finds any
                  provision of these Business Terms, or portion thereof, to be
                  unenforceable, that portion shall be enforced to the maximum
                  extent permissible so as to give effect to the intent of the
                  parties (Us and You collectively) as reflected by that
                  provision. The remainder of the Business Terms shall continue
                  in full force and effect.
                </p>
              </div>
              <div>
                <p>
                  No provision of these Business Terms shall be deemed to be
                  waived and no breach excused unless such waiver or consent
                  shall be in writing and signed by Us. Any consent by Us to, or
                  a waiver by Us of, any breach committed by You, whether
                  expressed or implied, shall not constitute consent to, waiver
                  of, or excuse for any other different or subsequent breach.
                </p>
              </div>
              <div>
                <p>
                  Except when expressly allowed, any use of Our content and any
                  reproduction, republication, uploading, posting, public
                  display, encoding, translation, transmission, or distribution
                  thereof (including "mirroring") to any other computer, server,
                  website or other medium, without Our express prior written
                  consent is not allowed.
                </p>
              </div>
              <div>
                <p>
                  We shall not be liable for any damages whatsoever arising out
                  of force majeure or other similar circumstances, directly or
                  indirectly affecting You. Examples of force majeure events are
                  real or potential labour disputes, governmental actions, war
                  or threat of war, sabotage, civil unrest, demonstrations,
                  fire, storm, flooding, explosion, earthquake, provisions or
                  limitations of materials or resources, inability to obtain the
                  relevant authorization, accident, and defect in electricity or
                  telecommunication network. Force majeure or other events
                  beyond Our control hindering, delaying or complicating the
                  maintenance of the Platform entitles Us to suspend or limit
                  the Platform until further notice.
                </p>
              </div>
              <div>
                <p>
                  The rights and obligations under the Business Terms which by
                  their nature should survive will remain in full effect after
                  the termination or expiration of the Terms.
                </p>
              </div>
              <div>
                <p>
                  No partnership, joint venture, or relationship of
                  employee/employer or franchisor/franchisee arises between You
                  and Us by reason of the Business Terms.
                </p>
              </div>
              <div>
                <p>
                  Any press release, publicity, or public announcement about the
                  parties’ relationship will require the prior written approval
                  of both parties.
                </p>
              </div>
              <div>
                <p>
                  Neither party may assign the Business Terms or its rights or
                  obligations under the Business Terms without the prior written
                  consent of the other party. However, You do agree that We have
                  the right to assign them without Your consent to Our
                  subsidiaries or in case of a merger, reorganization,
                  acquisition, or other transfer of all or substantially all of
                  Our assets or voting securities. Subject to the foregoing, the
                  Business Terms will bind and inure to the benefit of each
                  party’s permitted successors and assigns.
                </p>
              </div>
              <div>
                <p>
                  <strong>Notices:</strong>
                </p>
                <p>
                  You may approach Saurabh Saraf, Grievance Officer, at
                  info@offsetfarm.io to address any queries, concerns,
                  discrepancies, or grievances with respect to Your information
                  or this Business Terms.
                </p>
                <p>
                  At our discretion, We may even choose to serve any notice or
                  communication to You by mail. In the case of notices sent by
                  mail, You will be deemed to have been served 5 (five) Business
                  Days after dispatch of the same.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "TermsOfUseBusiness",
};
</script>

<style scoped>
.main {
  margin-left: 77px;

  margin-top: 20px;
  font-family: "Lato" !important;
}

.upper-div {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.logo {
  margin-top: 30px;
}

.main-body {
  margin-top: 14px;
  display: flex;
  flex-direction: row;
  gap: 100px;
}

ul {
  list-style-type: none;
}

.sidebar {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.sidebar-content {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-left: 15px;
}

.policy-content-box {
  margin-top: 10px;

  height: 400px;
  overflow-y: scroll;
  border: 1px solid #ccc;
  padding-left: 10px;
  padding-right: 10px;
  padding-bottom: 10px;
  width: 655px;
}

.active {
  color: rgba(91, 112, 175, 1);
}

.policy-body {
  margin-left: 400px;
  width: 55%;
  height: 600px;
}

.last-updated {
  font-size: 18px;
  font-weight: 600;
  line-height: 21.6px;
  color: rgba(91, 112, 175, 1);
}

.message-1 {
  font-size: 18px;
  font-weight: 400;
  line-height: 21.6px;
}

.introduction {
  font-weight: 600;
  font-size: 26px;
  line-height: 31.2px;
}

.policy-content {
  font-size: 18px;
  line-height: 21.6px;
  margin-top: 15px;
  margin-left: 3px;
  display: flex;
  flex-direction: column;
  gap: 18px;
  text-align: justify;
  font-family: Lato !important;
}

.bold {
  font-weight: 600;
}

@media (max-width: 768px) {
  .main {
    margin-left: 0;
    margin-top: 0;
  }

  .main-body {
    margin-top: px;
    display: relative;
  }

  .policy-body {
    margin-left: 5px !important;
    margin-top: 200px !important;
    height: 600px;
  }
  .upper-div {
    width: 22rem;
    margin-left: -50px;
  }
  .policy-content-box {
    margin-left: -50px;
    width: 22rem;

    height: 400px;
  }
  .message-1 {
    margin-bottom: 10px;
  }
}
</style>
