<template>
  <div class="main">
    <div class="main-body">
      <div class="policy-body">
        <div class="upper-div">
          <h1>Terms of Use (Users)</h1>

          <p class="last-updated">Last updated: October 29, 2023</p>

          <p class="message-1">
            This Privacy Policy includes important information about your
            personal data and we encourage you to read it carefully.
          </p>
        </div>

        <div class="inner-div">
          <div class="policy-content-box">
            <div class="policy-content">
              <div>
                <div class="bold">INTRODUCTION</div>
                These terms of use (“Terms”) apply to the Services (defined
                hereunder) provided by Regenfi Labs Private Limited, a private
                limited company, incorporated under the provisions of the
                Companies Act, 2013, having its registered office at House No.
                43, Block- G, Landmark NA Sultanpuri, New Delhi - 110041, India
                (“Company” or “We” or “Us” or “Our”).
              </div>
              <div>
                For the purpose of these Terms, wherever the context so requires
                the term “You”, “Your”, or “User”, shall mean any person who is
                an end-user and includes the individual whose data is shared on
                the Platform, who visits, uses or accesses the Platform, creates
                the Account (defined hereunder).
              </div>

              <div>
                The Terms contained in this electronic record read with the
                Privacy Policy, as available and uploaded on the Platform
                (“Privacy Policy”), or any specific terms and conditions, as
                applicable or relating to the Services which are incorporated
                herein by reference, shall constitute the entire legally and
                binding agreement between You and Us, in connection with the
                access, visit, or usage of the Platform for availing the
                Services in any manner unless a mutual agreement executed
                between You and Us states otherwise.
              </div>

              <div>
                Before using Our Services, We need to obtain Your unequivocal
                agreement to these Terms. You are requested to read these Terms
                carefully before accepting them.
              </div>
              <div>
                This electronic record is generated by a computer system and
                does not require any physical or digital signatures. This
                electronic record is published in accordance with the relevant
                provisions of the Information Technology Act, 2000 (“IT Act”)
                and rules made thereunder.
              </div>

              <div class="bold">
                IN CASE YOU DO NOT AGREE WITH THESE TERMS, THEN PLEASE REFRAIN
                FROM USING AND ACCESSING THE PLATFORM AND/OR AVAILING OUR
                SERVICES.
              </div>

              <div>
                It is further clarified that by availing the Services on the
                Platform, and/or visiting, viewing, accessing, or otherwise
                using the Services or information created, collected, compiled,
                or submitted to the Platform, You are deemed to have agreed to
                these Terms and all the policies of the Platform.
              </div>

              <div>
                It is hereby clarified that We may, from time to time, change
                provisions related to the Services which also include changing
                the extent and scope of Services and/ or including any other
                category of service or facility within the term ‘Services’, at
                Our sole discretion. You can determine when these Terms were
                last revised by referring to ‘LAST UPDATED’ mentioned in these
                Terms. Your continued use of the Platform shall be deemed to
                signify Your acceptance of these provisions or amended
                provisions of these Terms.
              </div>

              <div class="bold">DEFINITIONS</div>

              <div>
                “Account” shall mean an account created by You on Our Platform
                to access the Services;
              </div>

              <div>
                “Business Day” shall mean any day other than a Sunday or a day
                on which scheduled commercial banks in New Delhi are authorized
                or required by Law to be closed.
              </div>

              <div>
                “Law” or “Laws” includes all applicable statutes, enactments,
                acts of the legislature or parliament, laws, ordinances, rules,
                by-laws, regulations, notifications, guidelines, policies,
                directions, directives, and orders of any Government Authority,
                tribunal, board or court, as amended from time to time, in
                India.
              </div>

              <div>
                “Services” shall mean to include but not be limited to
                information technology-related support provided by Us to You in
                order to create a database for Your ease of reference so as to
                enable project management such as its collection, processing,
                and reporting;
              </div>

              <div>
                “Person” shall mean any natural person, limited or unlimited
                liability company, corporation, partnership (whether limited or
                unlimited), proprietorship, Hindu Undivided Family, trust,
                union, association, society, foundation, Government, or any
                agency or political subdivision thereof or any other entity that
                may be treated as a person under applicable Law.
              </div>

              <div>
                “Platform” shall mean an information technology platform i.e.,
                both mobile-based application and website-based application,
                that is inter alia engaged in providing Services to the Users on
                or through the Platform.
              </div>

              <div>INTERPRETATION</div>

              <div>
                Any reference to the singular includes a reference to the plural
                and vice versa; any reference to one gender includes a reference
                to other gender(s) unless explicitly stated otherwise.
              </div>
              <div>
                Headings and captions are used for convenience only and not for
                interpretation of the Terms.
              </div>

              <div>
                Any reference to a natural person shall include his/her heirs,
                executors, and permitted assignees and any reference to a
                juristic person shall, include its affiliates, successors, and
                permitted assignees, unless repugnant to the context.
              </div>

              <div>CREATING AN ACCOUNT</div>

              <div>
                Please note that in order to avail the Services, You are
                required to create a User account (“Account”) on the Platform
                and become a registered user. Certain information such as the
                name, mobile number, and e-mail ID is required to create an
                account on the Platform for the purposes of Your identity
                verification.
              </div>

              <div>
                You agree that You shall provide accurate and correct
                information at the time of sign-up and You shall also update
                such information and data, from time to time, in case of any
                change thereto and/ or as and when required and asked by the
                Platform in this regard. If You provide any information that is
                untrue, inaccurate, not current, incomplete or We have
                reasonable grounds to suspect that such information is untrue,
                inaccurate, not current or incomplete, or not in accordance with
                the Terms herein and the other policies of Platform, We shall
                have the right to indefinitely suspend or terminate Your Account
                or block Your access on the Platform.
              </div>

              <div>
                You shall log out from Your Account at the end of each session
                in order to ensure complete security and secrecy of Your data
                and Our data. You shall solely be responsible for safeguarding
                the Account, password, and all the information and data
                associated with such Account. For the safety of the data, and
                information in such Account and prevention of any possibility of
                any unauthorized use thereof, it is suggested that You use a
                strong password and not disclose the password to any third
                parties.
              </div>

              <div>
                You are solely responsible for maintaining the confidentiality
                of Your Account, display name, and password and You are fully
                responsible for all activities that occur under the same and We
                shall not be liable or responsible whatsoever in this regard.
                You expressly agree that You will immediately notify Us about
                any actual or potential unauthorized use of Your Account,
                display name and password, or any breach of security or any
                breach of the Terms by a third party.
              </div>

              <div>
                If We reasonably believe that an account and password is being
                used or misused in any manner, We reserve the right to cancel
                rights to access the Platform immediately without notice and
                block access to all users from that particular IP address. You
                agree to notify us and the Platform immediately of any
                unauthorized use of Your Account or any other breach of
                security. We shall not be liable for any loss that You may incur
                as a result of someone else using Your password or Account.
                However, You could be held liable for all the losses, claims,
                and liabilities incurred by the Us due to someone else using
                Your Account or password.
              </div>

              <div>
                In the event You become aware of any breach of security or
                unauthorized use of the Account, then You shall take all the
                reasonable steps to inform Us with respect to such unauthorized
                use of the Account and, in this regard, We shall not be
                responsible for any liabilities that such You may incur from the
                misuse of the Account or password or any data and information
                contained therein. You agree that We cannot and will not be
                liable for any loss or damage arising from Your failure to
                comply with these Terms. In this respect, You shall indemnify Us
                for losses that We may incur from any other party on account of
                such unauthorized or fraudulent use of the Account.
              </div>

              <div>PRIVACY</div>
              <div>
                You agree that during Your use and access of the Platform and/or
                availing of the Services, You will provide Us with certain
                information and other data as mentioned under the Terms which
                may or may not be otherwise publicly available. Please note that
                We respect the privacy and confidentiality of such data. Your
                private information and data as provided by You under these
                Terms are governed by the Privacy Policy.
              </div>

              <div>
                By using and visiting the Platform and/or availing the Services,
                You agree to the terms and conditions of Our Privacy Policy.
                Regarding Your personal information and data, We will only
                collect, use, disclose, or process such information and data in
                accordance with our Privacy Policy, which You accept by Your use
                and access of the Platform and/or availing the Services.
              </div>

              <div>CONDITIONS TO USE THE PLATFORM</div>

              <div>
                These Platform shall be used by You subject to the following:
              </div>

              <div>
                Compliance with applicable Law: You agree that You will act
                lawfully, diligently, and honestly at all times when You access
                and use the Platform and/or avail the Services and will comply
                with Laws.
              </div>

              <div>
                Modification of the Terms: Subject to applicable Law, We may
                stop providing Services (or any part of Services) permanently or
                temporarily, to You or may modify or change the nature of
                Services and/or these Terms without any prior notice to You.
                Your use of Services following such modification shall
                constitute Your deemed acceptance of such modifications.
                Suspension of whole or part of Our Services, either permanently
                or temporarily does not absolve You or others of any liabilities
                incurred pursuant to breach of these Terms.
              </div>

              <div>
                Age: For the use and access of the Platform, whether or not for
                provisions of availing any of the Services on the Platform, You
                must be 18 (eighteen) years of age or older to use or visit the
                Platform, in any manner. For this purpose, You agree that by
                visiting the Platform or accepting these Terms, You represent
                and warrant to Us that You are 18 (eighteen) years of age or
                older and that You have the right, authority, and capacity to
                use the Platform and agree to and abide by the Terms as provided
                herein.
              </div>

              <div>
                Further, the use of and access to the Platform can be availed
                only by such individuals who can form and enter into a valid
                ‘contract’ as per the conditions provided under the Indian
                Contract Act, 1872. It is hereby expressly clarified that the
                persons who are ‘incompetent to contract’ within the meaning of
                the Indian Contract Act, 1872, including minors, un-discharged
                insolvents, etc. are not eligible to use the Platform.
              </div>

              <div>
                While individuals under the age of 18 may use or visit the
                Platform or avail the Services of the Platform, they shall do so
                only with the involvement, supervision, control, and guidance of
                their parents or legal guardians. We reserve the right to deny
                the use of/access to and/or exclude from our Platform, any
                person at Our absolute discretion. We also reserve the right to
                suspend, revoke, or amend Your use/membership at Our absolute
                discretion.
              </div>

              <div>
                Your Rights: We do not claim any ownership of the information
                that You submit through Your Account or through Us. You may have
                the necessary rights to such information, including the right to
                grant the rights and licenses as required by these Terms. It is
                hereby clarified that all Your information and Your content will
                belong solely to You and only be used to enhance the provision
                of Services. You are responsible for any data or content
                uploaded by You onto the Platform. We do allow You to share Your
                information with others, and by doing so, You acknowledge that
                We will not be responsible for any misuse of it once it is
                shared or made public. We reserve the right to edit or remove
                any material submitted/posted to the Platform, stored by You on
                Our servers, or hosted or published on the Platform.
              </div>

              <div>
                Our Rights: We own all copyrights, trademarks, domains, logos,
                trade dress, trade secrets, patents, and other intellectual
                property rights associated with our Company. You may not use Our
                copyrights, trademarks (or any similar marks), domains, logos,
                trade dress, trade secrets, patents, and other intellectual
                property rights unless You have Our express written permission.
              </div>

              <div>
                Your license to Us: In order to operate and provide the Services
                to You, You hereby grant Us a worldwide, non-exclusive,
                royalty-free, sub-licensable, and transferable right to use,
                reproduce, distribute, and create derivative works of Your
                information to enhance and improve our Services.
              </div>

              <div>
                No disruption or harm to the Platform and/or Services: You agree
                that You will not interfere with, jeopardize, disrupt, or harm
                the Platform and/or Services and that You will not intercept,
                expropriate, re-use, steal, or re-utilize any system, data, or
                information comprised in or provided to You via the Platform
                and/or Services and at all times comply with the Terms and other
                policies of the Platform.
              </div>

              <div>
                Access to the Platform: We will provide You with any help You
                may reasonably require to access the Platform but We shall not
                be responsible if You are unable to access any section of the
                Platform or any of the Services for any reason. We do not
                guarantee You access to the Platform at any time and at all
                times. We do not guarantee that while You are accessing the
                Platform, Your access will be uninterrupted, without
                delay/interference, secure and/or error-free, or operate as set
                out and anticipated in these Terms. Accordingly, We reserve the
                right, at any time, to suspend or discontinue the Platform
                and/or any of the Services for any reason without incurring any
                liability or obligation to You.
              </div>

              <div>
                Communication: By using the Platform, You consent to receive
                communications via electronic records from Us periodically and
                as and when required including: (a) notices about Your Account,
                password changes, payment authorizations, and other
                transactional information; (b) notices about updates to Our
                Terms; and (c) information about products, services, surveys,
                events, news, and promotions offered by Us where permitted by
                applicable Law. If You do not wish for Us to communicate with
                You regarding (c) above, You may opt out of future
                communications by clicking the “unsubscribe” link in any such
                communication. We may even, at Our sole discretion, suspend the
                User’s ability to use or access the Platform at any time while
                We investigate complaints or alleged violations of these Terms
                or for any other reason.
              </div>

              <div>
                Fees and Taxes: You are responsible for all carrier data plans,
                internet fees, and other fees and taxes associated with Your use
                of Our Services or Platform.
              </div>

              <div class="bold">7. PLATFORM SERVICES</div>

              <div>
                You, after logging into the Account will be able to use the
                Services. We do not guarantee any verification of any data or
                any other information shared by the User on the Platform. We
                provide a medium to enhance transparency in data collection and
                its analyses of the information for the ease of understanding of
                the User. We do not guarantee the authenticity, or reliability
                of the information and consider it as bonafidely secured
                information. In this regard, We shall not be responsible for any
                liabilities that may arise from the misuse of the information by
                the User, and the User must at all times, indemnify Us in case
                of such allegations.
              </div>

              <div>
                You are provided with tech-enabled system-generated assistance
                in measurement, reporting, and verification so that You get a
                fair idea about the status of Your project and are able to plan
                accordingly. We do not guarantee any authenticity regarding the
                output that is system-generated and is based on the information
                shared by You. We shall not be responsible for any liabilities
                that may arise from the reliance on the Information generated
                through the usage of the Services, and You must at all times,
                indemnify Us in case of such claims.
              </div>

              <div>
                You hereby acknowledge that it is solely responsible for the
                generated content and shall be solely liable for any
                consequences arising out of using the Services by providing
                information and sharing such generated content, including, but
                not limited to any claims, costs, losses, damages, expenses,
                judgments, any other possible conflicts, disputes, or issues
                arising out of or related to such generated content.
              </div>

              <div>
                We use the information that We have only for enhancing Your
                experience and only to the extent necessary in providing the
                Services.
              </div>

              <div>
                We work to protect the safety, security, and integrity of Our
                Users. This includes appropriately dealing with abusive people
                and activity violating Our Terms. We work to prohibit misuse of
                the Company including harmful conduct towards others, and
                violating Our Terms and policies, and address situations where
                We may be able to help support or protect Our community. If We
                learn of people or activities like this, We will take
                appropriate action, including removing such people or activities
                or contacting law enforcement. Any such removal will be in
                accordance with these Terms. We aim to adhere to the security
                measures as specifically provided in the Privacy Policy.
              </div>

              <div class="bold">CODE OF CONDUCT</div>

              <div>
                Under these Terms, You agree not to host, display, upload,
                modify, publish, transmit, update, or share any information
                that:
              </div>

              <div>
                <ul>
                  <li>
                    belongs to another Person and in relation to which it does
                    not have any right of use;
                  </li>
                  <li>
                    infringes intellectual property rights (including any
                    patent, trademark, copyright, or other proprietary rights)
                    of any Person and privacy rights of any individual;
                  </li>
                  <li>is false or misleading in any way;</li>
                  <li>violates any Law;</li>
                  <li>harasses or advocates harassment of another Person;</li>
                  <li>
                    promotes illegal activities or abusive, obscene, defamatory,
                    or libelous conduct;
                  </li>
                  <li>solicits illegal activities;</li>
                  <li>harms minors in any way;</li>
                  <li>
                    deceives or misleads the other Users of the Platform about
                    the origin of messages or communicates any information which
                    is grossly offensive or menacing in nature;
                  </li>
                  <li>
                    threatens the unity, integrity, defense, security, or
                    sovereignty of India, friendly relations with foreign
                    states, or public order or causes incitement to the
                    commission of any cognizable offense or prevents
                    investigation of any offense or is insulting any other
                    nation;
                  </li>
                  <li>
                    promotes an illegal or unauthorized copy of another Person's
                    copyrighted work;
                  </li>
                  <li>
                    provides material that exploits people in a sexual, violent,
                    or otherwise inappropriate manner or solicits personal
                    information from anyone;
                  </li>
                  <li>
                    provides instructional information about illegal activities
                    such as making or buying illegal weapons, violating
                    someone’s privacy, or providing or creating computer
                    viruses;
                  </li>
                  <li>
                    tries to gain unauthorized access or exceeds the scope of
                    authorized access to the Platform or solicits passwords or
                    personal identifying information for commercial or unlawful
                    purposes from other users;
                  </li>
                  <li>
                    refers to any website or URL that, in our sole discretion,
                    contains material that is inappropriate for the Platform or
                    any other website, application, or software that contains
                    content that would be prohibited or violates the letter or
                    spirit of these Terms.
                  </li>
                </ul>
              </div>

              <div>
                <p>You also agree not to:</p>
              </div>

              <div>
                <ul>
                  <li>
                    reveal/disclose confidential or proprietary information of
                    other Users, the Company, Platform, or any third party when
                    You receive or come in possession of such confidential or
                    proprietary information;
                  </li>
                  <li>
                    Incorporate any computer contaminant, software virus, or any
                    computer code, file, or program on the Platform designed to
                    interrupt, destroy, or limit the functionality of the
                    Platform or hamper Our Services;
                  </li>
                  <li>
                    incorporate or introduce any program on the Platform that
                    might infringe the intellectual property rights of any other
                    user and/or of the Company;
                  </li>
                  <li>
                    download, copy, reproduce any file or information available
                    on the Platform which the User knows, or reasonably should
                    know, cannot be legally reproduced, displayed, performed,
                    and/or distributed;
                  </li>
                  <li>
                    in any way, deface or vandalize the Platform or prevent or
                    restrict others from using the Platform or availing Our
                    Services;
                  </li>
                  <li>
                    infringe any patent, trademark, copyright or other
                    proprietary rights or third party’s trade secrets or rights
                    of publicity or privacy, of the Company/ Platform, other
                    users of the Platform or any third Party. We agree that it
                    has valid rights and title in any and information and has
                    not infringed on any intellectual property rights belonging
                    to any Person and, in this respect, You agree that it will
                    indemnify the Company or its affiliates for all claims
                    arising out of any information it posted on the Platform;
                  </li>
                  <li>
                    impersonate any Person or entity, or falsely state or
                    otherwise misrepresent themselves or their affiliation with
                    any Person or entity;
                  </li>
                  <li>
                    directly or indirectly, offer, attempt to offer, trade or
                    attempt to trade in any item, the dealing of which is
                    prohibited or restricted in any manner under the provisions
                    of any applicable Law; and
                  </li>
                  <li>
                    create liability on Us or cause Us to lose (in whole or in
                    part) the services of its internet service provider or other
                    suppliers.
                  </li>
                </ul>
              </div>

              <div>
                <p>
                  It is also clarified that You shall not use any “deep-link”,
                  “page-scrape”, or use any other automatic device, program,
                  algorithm, or methodology, or any similar or equivalent manual
                  process, to access, acquire, copy, or monitor any portion of
                  the Platform, or in any way reproduce or circumvent the
                  navigational structure or presentation of the Platform or any
                  Service, to obtain or attempt to obtain any materials,
                  documents, or information through any means not purposely made
                  available through the Platform. We reserve the right to bar
                  any such activity.
                </p>
              </div>

              <div>
                <p>
                  You agree that You shall not attempt to gain unauthorized
                  access to any portion or feature of the Platform or any
                  feature pertaining to availing of Services or any other
                  systems or networks connected to the Platform or to any
                  server, computer, network, or to any Services offered on or
                  through the Platform, by hacking, password “mining” or any
                  other illegitimate means.
                </p>
              </div>

              <div>
                <p>
                  You agree that You shall not probe, scan, or test the
                  vulnerability of the Platform or any network connected to the
                  Platform nor breach the security or authentication measures on
                  the Platform or any network connected to the Platform. You may
                  not reverse look-up, trace, or seek to trace any information
                  on any other user of or visitor to the Platform, or any other
                  client/customer/user/member of the Company/Platform including
                  any account on the Platform not owned/operated/managed by You,
                  to its source, or exploit the Platform or information made
                  available or offered by or through the Platform, in any way
                  where the purpose is to reveal any information, including but
                  not limited to personal identification or information, other
                  than Your own information, as provided for by the Platform.
                </p>
              </div>

              <div>
                <p>
                  You agree that You shall not make any negative, denigrating,
                  or defamatory statement and/or comment about Us or Our
                  Services or the brand name or domain name used by Us or
                  otherwise engage in any conduct or action that might tarnish
                  Our image or Our reputation or that of other Users on the
                  Platform or Our other business partners or otherwise tarnish
                  or dilute any of the Our trade or service marks, trade names
                  and/or goodwill associated with such trade or service marks,
                  trade name as may be owned or used by Us.
                </p>
              </div>

              <div>
                <p>
                  You agree that You will not use the Platform or any content
                  thereof for any purpose which is unlawful or prohibited by the
                  Terms or to solicit the performance of any illegal activity or
                  other activity which infringes Our rights, that of Our users
                  and/or third parties.
                </p>
              </div>

              <div>
                <p>
                  In the event, We have reasonable grounds to believe that Your
                  activities include any of the acts specified above, we may
                  initiate appropriate legal action against You as well as
                  notify the relevant regulatory or law enforcement authorities
                  where appropriate in addition to any other available remedies
                  under law or equity, apart from restricting or suspending or
                  terminating Your use of the Platform.
                </p>
              </div>

              <div>
                <p>
                  You agree that You shall, at all times, ensure full compliance
                  with the applicable provisions of the IT Act, and the rules
                  thereunder as applicable and as amended from time to time and,
                  also all applicable Laws regarding the use of Services.
                  Further, You agree that You shall not solicit (directly or
                  indirectly) any other Users of the Platform to avail the
                  Services of the Platform being displayed on the Platform,
                  either independently or through Us or Our Platform.
                </p>
              </div>

              <div>
                Please note that You can avail the Services on the Platform by
                making payments to Us. For the purpose of making payments
                towards any fee, the User can make such payments by (a)
                Credit/Debit Card; (b) Net Banking; or (c) any other mode of
                electronic payment as provided on the Platform.
              </div>

              <div>
                Any payments and transactions in respect of Service(s) under
                these Terms may be facilitated by or through third-party payment
                processors, online fund transfer facilities through banks or
                credit cards or mobile and internet-based payment /commerce
                platforms or authorized payment gateway networks as recognized
                and authorized by the Reserve Bank of India (“Payment
                Facilitators”).
              </div>

              <div>
                In this respect, it is clarified that the services of Payment
                Facilitators are utilized for the purposes of making any payment
                transaction in respect of Service(s) under these Terms, and use
                of such services of Payment Facilitators shall not render the
                Platform liable or responsible or assume any liability,
                whatsoever in respect of any loss or damage, arising directly or
                indirectly to You on account of (i) lack of authorization for
                any transaction(s); (ii) exceeding the pre-set limit mutually
                agreed by and between You and Your bank; (iii) any payment
                issues arising out of the transaction; (iv) decline of
                transaction for any reason; or (v) for any reason whatsoever.
              </div>

              <div>
                All payments made in respect of Services shall be subject to
                applicable tax Laws of India.
              </div>

              <div>
                <strong>PAYMENT TERMS</strong>
                <p>
                  Please note that You can avail the Services on the Platform by
                  making payments to Us. For the purpose of making payments
                  towards any fee, the User can make such payments by (a)
                  Credit/Debit Card; (b) Net Banking; or (c) any other mode of
                  electronic payment as provided on the Platform.
                </p>
                <p>
                  Any payments and transactions in respect of Service(s) under
                  these Terms may be facilitated by or through third-party
                  payment processors, online fund transfer facilities through
                  banks or credit cards or mobile and internet-based
                  payment/commerce platforms or authorized payment gateway
                  networks as recognized and authorized by the Reserve Bank of
                  India (“Payment Facilitators”).
                </p>
                <p>
                  In this respect, it is clarified that the services of Payment
                  Facilitators are utilized for the purposes of making any
                  payment transaction in respect of Service(s) under these
                  Terms, and use of such services of Payment Facilitators shall
                  not render the Platform liable or responsible or assume any
                  liability, whatsoever in respect of any loss or damage,
                  arising directly or indirectly to You on account of (i) lack
                  of authorization for any transaction(s); (ii) exceeding the
                  pre-set limit mutually agreed by and between You and Your
                  bank; (iii) any payment issues arising out of the transaction;
                  (iv) decline of transaction for any reason; or (v) for any
                  reason whatsoever.
                </p>
                <p>
                  All payments made in respect of Services shall be subject to
                  applicable tax Laws of India.
                </p>
                <p>
                  Subject to clause 14.6 of these Terms, in the event of any
                  claim for refund by You for any reason whatsoever, You shall
                  immediately intimate Us of the same. We shall duly assess Your
                  concern and determine the genuineness of it. If we determine
                  that any refund (excluding any transaction charges or other
                  such charges) if payable to You, then such refund (if any)
                  shall be effected by Us via Payment Facilitators or such other
                  means as We deem appropriate. No claims for refund shall be
                  made by You to the Payment Facilitator directly, and no such
                  claims shall be entertained by Us.
                </p>
              </div>

              <div>
                <strong>INDEMNITY</strong>
                <p>
                  In addition and not in derogation of the specific indemnities
                  provided by You to Us under these Terms and/or policies of the
                  Platform, You agree to indemnify, defend, and hold Us and Our
                  affiliates, officers, directors, employees, consultants,
                  representatives, shareholders, contractors, users, and agents
                  etc. harmless against any or all losses, liabilities, claims,
                  damages, demands, costs, and expenses (including legal fees
                  and disbursements in connection therewith and interest
                  chargeable thereon) arising out of or in connection with any
                  claim, suit, action, or other proceeding brought against Us or
                  such party, to the extent such losses are based on or arising
                  out of or in connection with:
                </p>
                <p>
                  • Any breach or non-performance of any of the Terms and/or
                  other policies of the Platform with respect to the use and
                  access of the Platform and/or availing of Services.
                </p>
                <p>
                  • Truthfulness and correctness of the information provided by
                  the User at the time of registration and/or at any time during
                  availing of the Services.
                </p>
                <p>
                  • Breach of any third-party rights (including, but not limited
                  to, claims in respect of defamation, invasion of privacy, or
                  infringement of any other intellectual property right) by You.
                </p>
              </div>

              <div>
                <strong>INTELLECTUAL PROPERTY RIGHTS</strong>
                <p>
                  For the purpose of these Terms herein, the term, “intellectual
                  property rights” shall mean on a worldwide basis, all patents,
                  copyrights, trade secrets, service marks, trademarks, trade
                  names, trade dress, trademark applications and registrations,
                  internet domain names, design rights, and all other
                  proprietary and intellectual property rights as may exist now
                  and hereafter come into existence, and all renewals and
                  extensions thereof, regardless of whether any of such rights
                  arise under any applicable law.
                </p>
                <p>
                  It is further acknowledged and agreed by You that all the
                  intellectual property rights in all material presented on the
                  Platform, including but not limited to text, audio, video or
                  graphical images, interfaces, graphics, design, compilation,
                  information, computer code, products, software, downloadable
                  software, trademarks, logos and all other materials appearing
                  on the Platform are Our property, that of Our parent,
                  affiliates, and associates and are protected under applicable
                  Laws.
                </p>
                <p>It is hereby clarified and agreed by You that:</p>
                <p>
                  • We own all the intellectual property rights in and relating
                  to the Services offered through the Platform, and Your use of
                  the Platform and/or availing of Services does not grant or
                  confer You with any rights in relation to Our intellectual
                  property rights or Our affiliates or licensor’s or suppliers’
                  intellectual property rights.
                </p>
                <p>
                  • The structure of Our Platform shall not be reproduced,
                  distributed, or published, in whole or in part, by You for any
                  purpose; other than in connection with Your private use of the
                  Platform and/or availing of Services, You shall not copy,
                  reproduce, download, publish, adapt, create derivative works,
                  re-publish, post, broadcast, record, print, commercially
                  exploit, transmit, edit, communicate to the public or
                  distribute in any other way, any intellectual property rights
                  or content in relation to the Platform and/or availing of the
                  Services or the computer codes or elements which comprise the
                  Platform.
                </p>
                <p>
                  • By using, accessing, or visiting Our Platform and/or
                  availing the Services, You acknowledge and agree that the
                  general layout, content, and design of the Platform is
                  protected by copyrights, trademarks, service marks, patents or
                  other proprietary rights and laws and these Terms do not grant
                  to You any rights to any intellectual property rights in
                  respect of the Platform or any content.
                </p>
                <p>
                  • You cannot create any derivative work or technology based
                  upon any Our intellectual property rights, confidential or Our
                  proprietary information.
                </p>
                <p>
                  • You cannot adapt or use any trademark, service mark, trade
                  name, logo, or domain name similar to or likely to be confused
                  with those of Ours or take any other action that infringes
                  upon or impairs Our trademark (whether registered or
                  unregistered) or other intellectual property rights.
                </p>
                <p>
                  • Other than as set out in this clause and the Platform’s
                  policies, You are not permitted to use any of Our intellectual
                  property rights without Our (and Our affiliates, licensor’s or
                  suppliers) prior written consent.
                </p>
                <p>
                  We may take action against You or with respect to Your
                  Account, including disabling or suspending Your Account if You
                  clearly or repeatedly infringe the intellectual property
                  rights of others or where We are required to do so for legal
                  reasons. Disabling or suspending Your Account will be in
                  accordance with these Terms and as per applicable Law.
                </p>
                <p>
                  You acknowledge that You are responsible for and will release
                  Us from any and all liabilities, losses, claims and damages
                  that may arise out of or in connection with any infringement
                  of intellectual property rights of the Company or third
                  parties, by You. You further agree to hold Us harmless and
                  indemnify Us in this regard.
                </p>
              </div>
              <div>
                <strong>TERMINATION</strong>
                <p>
                  You agree that We, at Our sole discretion and for any,
                  including inter alia without limitation if You breach these
                  Terms, may terminate Your access to and use of the Platform,
                  at any time. You agree that any termination of Your access to
                  the Platform and/or suspension/termination of Your Account may
                  be effected without prior notice, and in this respect, We
                  shall not be liable to You for any such termination. Your
                  right to use the Platform immediately ceases upon termination
                  of Your access/use of the Platform.
                </p>
                <p>
                  The provisions of these Terms shall continue to apply until
                  terminated by either of the Party. In case of User wanting to
                  terminate these Terms, the User may do so by: (a) not
                  accessing the Platform; or (b) closing the Account.
                </p>
                <p>
                  We reserve the right to, at any time, and with or without
                  notice, terminate these Terms against each of the Users, if
                  there is:
                </p>
                <p>
                  • breach of any of the applicable Laws: or the provisions of
                  these Terms or the terms of the Privacy Policy or any other
                  terms, conditions, or policies that may be applicable to the
                  User from time to time (or have acted in a manner that clearly
                  shows that the User does not intend to, or is unable to,
                  comply with the same);
                </p>
                <p>
                  • Platform is unable to verify or authenticate any information
                  provided to the Platform by the User;
                </p>
                <p>
                  We believe, at Our sole discretion, that the User’s actions
                  may cause legal liability to the Company/ Platform, (or any of
                  its affiliates, independent contractors, service providers,
                  consultants, licensors, agents, and representatives) or that
                  they are contrary to the interests of the Platform;
                </p>
                <p>We are required to do so by law; or</p>
                <p>
                  if You fail to provide (or after providing such consent, later
                  revokes) the consents necessary or desirable for the Company
                  to provide the Services to You.
                </p>
              </div>

              <div>
                <strong>LIMITATION OF LIABILITY</strong>
                <p>
                  You shall have access to the Platform and avail the Services
                  provided on the Platform voluntarily and at Your own risk. We
                  shall, under no circumstances be held responsible or liable on
                  account of any loss or damage sustained (including but not
                  limited to any accident, injury, death, loss of property) by
                  You or any other person or entity during the course of access
                  to the Platform’s Services.
                </p>
                <p>
                  By accessing the Platform and/or availing the Services, You
                  hereby release from and agree to indemnify Us and/or any of
                  Our directors, employees, partners, associates, and licensors,
                  from and against all liability, cost, loss or expense arising
                  out of their access to the Platform and availing of Services
                  including (but not limited to) personal injury and damage to
                  property and whether direct, indirect, consequential,
                  foreseeable, due to some negligent act or omission on their
                  part, or otherwise.
                </p>
                <p>
                  You shall be solely responsible for any consequences which may
                  arise due to their access of the Platform and availing of the
                  Services by conducting an illegal act or due to non-conformity
                  with these Terms and other rules and regulations in relation
                  to Services and/or policies of the Platform, including
                  provision of incorrect address or other personal details.
                </p>
                <p>
                  In consideration of Us allowing You to access the Services, to
                  the maximum extent permitted by law, You waive and release
                  each and every right or claim, all actions, causes of actions
                  (present or future) each of them has or may have against Us,
                  Our respective agents, directors, officers, business
                  associates, group companies, sponsors, employees, or
                  representatives for all and any injuries, accidents, or
                  mishaps (whether known or unknown) or (whether anticipated or
                  unanticipated) arising out of the provision of Services.
                </p>
                <p>
                  In no event shall We, or Our officers, directors, employees,
                  or partners be liable to You or any third party for any
                  special, incidental, indirect, consequential or punitive
                  damages whatsoever, including those resulting from loss of
                  use, data or profits, whether or not foreseeable or whether or
                  not we have been advised of the possibility of such damages,
                  or based on any theory of liability, including breach of
                  contract or warranty, negligence or other tortious action, or
                  any other claim arising out of or in connection with Your use
                  of or access of the Platform and availing of the Services.
                </p>
                <p>
                  You are responsible for and release Us from any and all
                  liabilities, losses, claims and damages that may arise out of
                  or in connection with the disclaimers as mentioned under these
                  Terms and further agrees to hold Us harmless and indemnify Us
                  in this regard.
                </p>
                <p>
                  In no event shall Our total aggregate liability to You for all
                  damages, losses, and causes of action (whether in contract or
                  tort, including, but not limited to negligence, strict
                  liability, product liability or otherwise) arising from these
                  Terms or any of Your use of the Platform exceed an aggregate
                  amount of INR 1000/- (Indian Rupees One Thousand only). We
                  accept no liability for any errors or omissions on behalf of
                  You. The foregoing limitations shall apply regardless of
                  whether (i) liability or damage is alleged for breach of
                  contract, tortious behavior, negligence, or under any other
                  theory or cause of action, and/or (ii) the party against which
                  liability or damages is sought was advised of the possibility
                  thereof.
                </p>
              </div>

              <div>
                <strong>DISCLAIMER</strong>
                <p>
                  YOU AGREE AND UNDERSTAND THAT THE PLATFORM IS PROVIDED BY US
                  ON AN “AS IS” AND “AS AVAILABLE” BASIS AND WE MAKE NO
                  REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
                  AS TO THE OPERATION OF THIS PLATFORM OR THE INFORMATION,
                  CONTENT INCLUDED ON THIS PLATFORM. YOU EXPRESSLY AGREE THAT
                  YOUR USE OF OUR PLATFORM IS AT YOUR SOLE RISK. WE RESERVE THE
                  RIGHT TO WITHDRAW OR DELETE ANY INFORMATION FROM THIS PLATFORM
                  AT ANY TIME AT OUR DISCRETION.
                </p>
                <p>
                  TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, WE
                  DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED. WE DO NOT WARRANT
                  THAT THIS PLATFORM, ITS SERVERS, OR EMAIL/OTHER COMMUNICATION
                  SENT FROM THE PLATFORM ARE FREE OF VIRUSES OR OTHER HARMFUL
                  COMPONENTS. THE COMPANY WILL NOT BE LIABLE FOR ANY DAMAGES OF
                  ANY KIND ARISING FROM THE USE OF THIS PLATFORM, INCLUDING, BUT
                  NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE AND
                  CONSEQUENTIAL DAMAGES.
                </p>
                <p>
                  TO THE EXTENT PERMITTED UNDER LAW, NEITHER US NOR OUR
                  PARENT/HOLDING COMPANY, SUBSIDIARIES, AFFILIATES, DIRECTORS,
                  OFFICERS, PROFESSIONAL ADVISORS, EMPLOYEES SHALL BE
                  RESPONSIBLE FOR THE DELETION, THE FAILURE TO STORE, THE
                  MIS-DELIVERY, OR THE UNTIMELY DELIVERY OF ANY
                  INFORMATION/CONTENT OR MATERIAL.
                </p>
                <p>
                  YOU AGREE THAT YOUR USE OF THE SERVICES SHALL BE AT YOUR SOLE
                  RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE, OUR
                  OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS EXCLUDE ALL
                  WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE
                  SERVICES AND YOUR USE THEREOF.
                </p>
                <p>
                  TO THE EXTENT PERMITTED UNDER LAW, WE SHALL NOT BE RESPONSIBLE
                  FOR ANY HARM RESULTING FROM DOWNLOADING OR ACCESSING ANY
                  INFORMATION/CONTENT OR MATERIAL AND THE QUALITY THEREOF.
                </p>
                <p>
                  NOTWITHSTANDING ANYTHING, WE DISCLAIM ANY AND ALL LIABILITY
                  AND RESPONSIBILITY FOR, AND IF A USER PAYS FOR ACCESS TOWARDS
                  COMPANY'S SERVICES, THEN THE USER WILL NOT BE ENTITLED TO A
                  REFUND AS A RESULT OF, ANY INACCESSIBILITY TO THE PLATFORM OR
                  UNAVAILABILITY OF THE SERVICES OR THAT IS CAUSED BY OUR
                  MAINTENANCE ON THE SERVERS OR THE TECHNOLOGY THAT UNDERLIES
                  OUR SITES, FAILURES OF OUR SERVICE PROVIDERS (INCLUDING
                  TELECOMMUNICATIONS, HOSTING, AND POWER PROVIDERS), DEFECT IN
                  TELECOMMUNICATION NETWORK, INTERNET FAILURES, COMPUTER
                  VIRUSES, NATURAL DISASTERS OR OTHER DESTRUCTION OR DAMAGE OF
                  OUR FACILITIES, ACTS OF NATURE, WAR, CIVIL DISTURBANCE, OR ANY
                  OTHER CAUSE BEYOND OUR REASONABLE CONTROL.
                </p>
                <p>
                  ANY MATERIAL/CONTENT ACCESSED, DOWNLOADED OR OTHERWISE
                  OBTAINED THROUGH THE PLATFORM IS DONE AT THE USER'S
                  DISCRETION, COMPETENCE, ACCEPTANCE AND RISK, AND THE USER WILL
                  BE SOLELY RESPONSIBLE FOR ANY POTENTIAL DAMAGE TO THE USER'S
                  COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM A USER'S
                  DOWNLOAD OF ANY SUCH MATERIAL/CONTENT.
                </p>
                <p>
                  THE PLATFORM SHALL MAKE BEST ENDEAVOURS TO ENSURE THAT THE
                  SERVICES ARE ERROR-FREE AND SECURE, HOWEVER, NEITHER THE
                  COMPANY NOR ANY OF ITS PARTNERS, LICENSORS OR ASSOCIATES MAKES
                  ANY WARRANTY THAT THE SERVICES WILL MEET USERS' REQUIREMENTS;
                  THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR
                  FREE; THE QUALITY OF THE SERVICES, INFORMATION/CONTENT, OR
                  OTHER MATERIAL THAT USERS OBTAIN THROUGH THE PLATFORM WILL
                  MEET USERS' EXPECTATIONS.
                </p>
                <p>
                  THE USER AGREES AND ACKNOWLEDGES THAT INFORMATION SHARED BY
                  THE USER SHALL BE THE PROPERTY OF THE USER AND THE USER SHALL
                  BE SOLELY RESPONSIBLE FOR ANY UNAUTHORIZED USE OR MISUSE OF
                  SUCH CONTENT AND SHALL INDEMNIFY AND HOLD HARMLESS THE COMPANY
                  FOR ANY CLAIM, DAMAGE, LOSS, EXPENSE BROUGHT AGAINST, ACCRUED
                  AND/OR INCURRED BY THE COMPANY IN THIS REGARD.
                </p>
                <p>
                  TO THE EXTENT PERMITTED UNDER LAW, IN THE EVENT OF SUSPENSION
                  OR CLOSURE OF ANY SERVICES, USERS SHALL NOT BE ENTITLED TO
                  MAKE ANY DEMANDS, OR CLAIMS, OF ANY NATURE WHATSOEVER.
                </p>
                <p>
                  PLATFORM HAS EXERTED REASONABLE EFFORTS TO ENSURE THAT ALL
                  INFORMATION PUBLISHED ON THE WEBSITE/APP IS ACCURATE AT THE
                  TIME OF POSTING; HOWEVER, THERE MAY BE ERRORS IN SUCH
                  INFORMATION FOR WHICH WE SHALL HAVE NO LIABILITY. WE RESERVE
                  THE RIGHT TO REMOVE OR ALTER ANY OF THE INFORMATION CONTAINED
                  ON THE PLATFORM AT OUR SOLE DISCRETION. THE PLATFORM CANNOT
                  GUARANTEE THE ADEQUACY, CURRENCY, OR COMPLETENESS OF THE
                  PLATFORM CONTENT.
                </p>
                <p>
                  YOU EXPRESSLY AGREES AND ACKNOWLEDGES TO HOLD US HARMLESS IN
                  RESPECT OF ANY COST, CLAIMS, DAMAGE, LOSS OR EXPENSES ACCRUED,
                  SUFFERED, INCURRED BY US OR ANY THIRD PARTY ARISING OUT OF OR
                  IN CONNECTION WITH ANY SUCH COMMUNICATION, INTERACTION,
                  DEALINGS AND TRANSACTIONS BETWEEN THE USER AND THIRD-PARTY
                  ADVERTISERS/THIRD PARTY SERVICE PROVIDERS. THE USER
                  ACKNOWLEDGES THAT WE DO NOT HAVE ANY CONTROL OVER SUCH
                  DEALINGS AND TRANSACTIONS AND PLAY NO DETERMINATIVE ROLE IN
                  THE PERFORMANCE WITH RESPECT TO THE SAME. THE COMPANY SHALL
                  NOT BE LIABLE FOR THE OUTCOMES OF SUCH COMMUNICATION,
                  INTERACTION, DEALINGS, AND TRANSACTIONS BETWEEN YOU AND THE
                  THIRD-PARTY ADVERTISERS/THIRD-PARTY SERVICE PROVIDERS.
                </p>
              </div>

              <div>
                <strong
                  >GOVERNING LAW, JURISDICTION AND DISPUTE RESOLUTION</strong
                >
                <p>
                  These Terms shall be governed by the Laws of India. Subject to
                  Clause 15.2 below, the courts and tribunals of New Delhi have
                  exclusive jurisdiction to settle any dispute arising out of or
                  in connection with these Terms (including any disputes
                  regarding the existence, validity, or termination of these
                  Terms).
                </p>
                <p>
                  If any dispute, controversy, or claim arises under, out of, or
                  in relation to these Terms, including any dispute concerning
                  the formation, construction, interpretation, or breach of
                  these Terms, then such dispute shall at the first instance be
                  attempted to be resolved through mutual good faith
                  consultations. If the dispute is not resolved in this manner
                  within forty-five (45) Business Days of either party (You or
                  Us) sending a notice in this regard to the other party of such
                  dispute, then the dispute shall be resolved by binding
                  arbitration under the provisions of the Arbitration &
                  Conciliation Act 1996, by a sole arbitrator who shall be
                  appointed by Us and whose decision shall be final and binding
                  upon all the concerned parties. The seat and venue of the
                  arbitration proceedings shall be New Delhi, India.
                </p>
              </div>

              <div>
                <strong>OTHER TERMS</strong>
                <p>
                  If for any reason, a court of competent jurisdiction finds any
                  provision of these Terms, or portion thereof, to be
                  unenforceable, that portion shall be enforced to the maximum
                  extent permissible so as to give effect to the intent of the
                  parties (Us and the User collectively) as reflected by that
                  provision. The remainder of the Terms shall continue in full
                  force and effect.
                </p>
                <p>
                  No provision of these Terms shall be deemed to be waived and
                  no breach excused unless such waiver or consent shall be in
                  writing and signed by Us. Any consent by Us to, or a waiver by
                  Us of, any breach committed by You, whether expressed or
                  implied, shall not constitute consent to, waiver of, or excuse
                  for any other different or subsequent breach.
                </p>
                <p>
                  Except when expressly allowed, any use of Our content and any
                  reproduction, republication, uploading, posting, public
                  display, encoding, translation, transmission, or distribution
                  thereof (including "mirroring") to any other computer, server,
                  website, or other medium, without Our express prior written
                  consent is not allowed.
                </p>
                <p>
                  We shall not be liable for any damages whatsoever arising out
                  of force majeure or other similar circumstances, directly or
                  indirectly affecting You. Examples of force majeure events are
                  real or potential labour disputes, governmental actions, war
                  or threat of war, sabotage, civil unrest, demonstrations,
                  fire, storm, flooding, explosion, earthquake, provisions or
                  limitations of materials or resources, inability to obtain the
                  relevant authorization, accident, and defect in electricity or
                  telecommunication network. Force majeure or other events
                  beyond Our control hindering, delaying, or complicating the
                  maintenance of the Platform entitles Us to suspend or limit
                  the Platform until further notice.
                </p>
                <p>
                  The rights and obligations under the Terms which by their
                  nature should survive will remain in full effect after the
                  termination or expiration of the Terms.
                </p>
                <p>
                  No partnership, joint venture, or relationship of
                  employee/employer or franchisor/franchisee arises between You
                  and Us by reason of the Terms.
                </p>
                <p>
                  At Our discretion, We may serve any notice or communication to
                  You by mail. In the case of notices sent by mail, You will be
                  deemed to have been served 5 (five) Business Days after
                  dispatch of the same.
                </p>
              </div>

              <div>
                <strong>GRIEVANCE OFFICER</strong>
                <p>
                  You may approach Saurabh Saraf, Grievance Officer, at
                  info@offsetfarm.io to address any queries, concerns,
                  discrepancies, or grievances with respect to Your information
                  or these Terms.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.main {
  margin-left: 77px;

  margin-top: 20px;
  font-family: "Lato" !important;
}

.logo {
  margin-top: 30px;
}

.upper-div {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.main-body {
  margin-top: 14px;
  display: flex;
  flex-direction: row;
  gap: 100px;
}

ul {
  list-style-type: none;
}

.sidebar {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.sidebar-content {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-left: 15px;
}
.policy-content-box {
  margin-top: 10px;

  height: 400px;
  overflow-y: scroll;
  border: 1px solid #ccc;
  padding-left: 10px;
  padding-right: 10px;
  padding-bottom: 10px;
}
.active {
  color: rgba(91, 112, 175, 1);
}

.policy-body {
  margin-left: 400px;

  width: 55%;
  height: 600px;
}

.last-updated {
  font-size: 18px;
  font-weight: 600;
  line-height: 21.6px;
  color: rgba(91, 112, 175, 1);
}

.message-1 {
  font-size: 18px;
  font-weight: 400;
  line-height: 21.6px;
}

.introduction {
  font-weight: 600;
  font-size: 26px;
  line-height: 31.2px;
}

.policy-content {
  font-size: 18px;
  line-height: 21.6px;
  margin-top: 15px;
  margin-left: 3px;
  display: flex;
  flex-direction: column;
  gap: 18px;
  text-align: justify;
  font-family: Lato !important;
}

.bold {
  font-weight: 600;
}
</style>
